### ISSUE TITLE
Add support for git-clean

### ISSUE THREAD

**Issue by tonybruess** [libgit2/rugged#164]
Please forgive me if I'm wrong, but I can't find support for http://www.kernel.org/pub/software/scm/git/docs/git-clean.html in rugged right now.

**Comment by clns** [comment]
See [Can I do git-clean with libgit2?](http://stackoverflow.com/questions/25205592/can-i-do-git-clean-with-libgit2) on SO. Based on that answer:

> libgit2 doesn't implement this itself. It's a porcelain command, which deals with interaction with the user. It also deals primarily with files which are of no interest to the Git repository.
>
> You can run status to see which files are untracked and then remove whichever ones the version of git-clean would have removed through the usual means available in your programming language.

**Comment by tonybruess** [comment]
Should this be closed then?
