### ISSUE TITLE
Is there a way to do get a rev list?

### ISSUE THREAD

**Issue by loveky** [libgit2/rugged#269]
I want to get a rev list with rugged like what I do `git rev-list commitA..commitB` 

Is there a way to do that?

Thanks!

**Comment by renotoaster** [comment]
I realize this is a closed issue, but this is exactly what I'm trying to do but I cannot figure out what you meant @carlosmn, meaning I cannot get it to work without eaching through the repo manually myself (walker returning all commits in the repo).

Say I have ten latest commits (first one being head):
```
abc123...0
abc123...1
<...>
abc123...9
```
And I want to get (for example) every commit between `abc123...2` and `abc123...7`.
With git's `rev-list` I can do just that as @loveky does. Can you give an example (in code) how to yield the commits between the two oid?

**Comment by zotherstupidguy** [comment]
same thing as @renotoaster 

updates?

**Comment by zar1** [comment]
@renotoaster @zotherstupidguy 

After struggling with this for a while, I ended up with something that I think does what we want

Assuming these are our commits from newest to oldest:

```
abc123blabla0
abc123blabla1
<...>
abc123blabla9
```

to get commits between blabla7 and blabla2, you do:

```
w = Rugged::Walker.new(repo)
w.push_range('abc123blabla7..abc123blabla2')
w.each {|commit| puts commit.oid}
```
