### ISSUE TITLE
Rugged::Credentials::SshKey - This transport isn't implemented

### ISSUE THREAD

**Issue by joelmoss** [libgit2/rugged#299]
From the latest development branch, the following does not work

``` ruby
require 'rugged'
creds = Rugged::Credentials::SshKey.new(username: 'git', publickey: File.expand_path("~/.ssh/id_rsa.pub"), privatekey: File.expand_path("~/.ssh/id_rsa"))
Rugged::Repository.clone_at 'ssh://github.com/joelmoss/strano.git', 'workspaces/joelmoss/strano', credentials: creds
```

```
Rugged::NetworkError: This transport isn't implemented. Sorry
```

Any ideas why? What am I missing here, as `Rugged::Credentials::Plaintext` works fine.

**Comment by mieciu** [comment]
Is there any possibility to verify whether current rugged gem installation already has ssh support?

**Comment by carlosmn** [comment]
`Rugged.features` shows a list of compiled-in optional features.

**Comment by mieciu** [comment]
Thank you @carlosmn  , I've opened an issue in my case, here:
https://github.com/libgit2/rugged/issues/484
Perhaps you could help me with determining the cause of error I'm facing there?
