### ISSUE TITLE
Error occuring when trying to clone github repo with SSH credentials using rugged

### ISSUE THREAD

**Issue by gabriel403** [libgit2/rugged#347]
When trying to clone a remote repo with Rugged, I keep getting the error 
`Failed to authenticate SSH session: Unable to open public key file`

I add my ssh credentials fine, but when I come to doing the clone the above error occurs.

```
cred = Rugged::Credentials::SshKey.new({username: 'gabriel403', publickey: publickey, privatekey: privatekey})
Rails.logger.debug cred
```

Where publickey and privatekey are string holding the keys.

```
repo = Rugged::Repository.clone_at('git@github.com:gabriel403/dotfiles.git', '/tmp/dotfiles', {credentials: cred})
Rails.logger.debug repo
```

**Comment by boblail** [comment]
> It is now possible to pass a keypair via a buffer instead of a path. For this, GIT_CREDTYPE_SSH_MEMORY and git_cred_ssh_key_memory_new() have been added.

It looks like support for this was added to libgit2 in 0.23.0

**Comment by arthurschreiber** [comment]
I'll add support for this asap.

**Comment by gabriel403** [comment]
💖

**Comment by boblail** [comment]
:star2: thanks!

**Comment by arthurschreiber** [comment]
@gabriel403 @boblail Check out https://github.com/libgit2/rugged/pull/501. It will only work with very recent versions of libssh2.
