### ISSUE TITLE
Rugged::Diff::Line

### ISSUE THREAD

**Issue by umdstu** [libgit2/rugged#353]
I"m trying to get a line by line diff (like git hubs gist revision page**) for any changed lines. When trying to determine whether to print a + or a - in the beginning of the line, I get an issue/bug. addition? and deletion? methods always return the same value, regardless of whether the line was added or deleted. i.e. for a line that was removed and replaced with  two other lines, the lines of the first hunk have ll.addition? == false. If using ll.deletion? , the lines of the second hunk == true. Am I doing this wrong? Is there a better way?

Class: Rugged::Diff::Line 
Method: - (Boolean) addition? OR - (Boolean) deletion?

```
<% head.diff(nil).each_patch do |pp| %>
    <% pp.each_hunk do |hh| %>
      <% hh.each_line do |ll| %>
        <%= ll.addition? %>
        <%= ll.old_lineno.to_s + "| " + " " + ll.content %><br>
      <% end %>
    <% end %>
  <% end %>
```

results in:

```
false 1| 1 
false 2| two 
false 3| 3 
false 4| four 
false 1| one
false 1| \ No newline at end of file 
```

*\* 
![screen shot 2014-04-16 at 8 20 34 am](https://cloud.githubusercontent.com/assets/1298036/2719445/de72418a-c560-11e3-9fd5-b5f9866bd962.png)

**Comment by mslinn** [comment]
Here is my version of working code, using rugged 1.5.1:

```ruby
repo = Rugged::Repository.new('.') 
head = repo.head
head.target.diff(head.target.parents.first).each_patch do |patch|
  patch.each_hunk do |hunk|
    hunk.each_line do |line|
      sign = line.addition? ? '+' : '-'
      lineno = line.old_lineno.to_s.rjust(4, ' ')
      p "#{sign} #{lineno}: #{line.content}"
    end
  end
end
```
