### ISSUE TITLE
Rugged::Repository.clone_at over ssh fails

### ISSUE THREAD

**Issue by albertsun** [libgit2/rugged#366]
```
/opt/ruby/rubies/ruby-2.0.0-p247/bin/ruby: symbol lookup error: /mnt/apps/capital_git/shared/bundle/ruby/2.0.0/bundler/gems/rugged-de19d5fb25fc/lib/rugged/rugged.so: undefined symbol: libssh2_session_init_ex
```

With the latest update of rugged, I'm now getting the above error from clone_at when using ssh credentials.

**Comment by ibestrest** [comment]
Hello. I installed the plugin on redmine "redmine_git_hosting". An error when I change the settings.
`/opt/bitnami/apps/redmine/htdocs/: symbol lookup error: /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/lib/rugged/rugged.so: undefined symbol: libssh2_session_init_ex`.
Can you help me?

**Comment by n-rodriguez** [comment]
bitnami@redmine:~/apps/redmine/htdocs/vendor$ cat ./bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged/mkmf.log
find_executable: checking for cmake... -------------------- yes

--------------------

find_executable: checking for gmake... -------------------- no

--------------------

find_executable: checking for make... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

package configuration for libgit2 is not found
"gcc -o conftest -I/opt/bitnami/ruby/include/ruby-2.0.0/x86_64-linux -I/opt/bitnami/ruby/include/ruby-2.0.0/ruby/backward -I/opt/bitnami/ruby/include/ruby-2.0.0 -I. -DAI_ADDRCONFIG=0 -I/bitnami/rubystack-linux-x64/output/sqlite/include -I/opt/bitnami/common/include -I/opt/bitnami/common/include/sasl -I/opt/bitnami/common/include   -I/opt/bitnami/common/include -fPIC -I/bitnami/rubystack-linux-x64/output/ImageMagick/include/ImageMagick -I/bitnami/rubystack-linux-x64/output/ImageMagick/include/ImageMagick -O3 -I/opt/bitnami/common/include/ImageMagick -I/opt/bitnami/common/include -I/opt/bitnami/common/include/ImageMagick -I/opt/bitnami/common/include  -g -Wall -Wno-comment conftest.c  -L. -L/opt/bitnami/ruby/lib -Wl,-R/opt/bitnami/ruby/lib -L. -L/bitnami/rubystack-linux-x64/output/sqlite/lib -L/opt/bitnami/common/lib -L/bitnami/rubystack-linux-x64/output/ImageMagick/lib -L/bitnami/rubystack-linux-x64/output/ImageMagick/lib -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -Wl,-R -Wl,/opt/bitnami/ruby/lib -L/opt/bitnami/ruby/lib -lruby-static  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/opt/bitnami/ruby/include/ruby-2.0.0/x86_64-linux -I/opt/bitnami/ruby/include/ruby-2.0.0/ruby/backward -I/opt/bitnami/ruby/include/ruby-2.0.0 -I. -DAI_ADDRCONFIG=0 -I/bitnami/rubystack-linux-x64/output/sqlite/include -I/opt/bitnami/common/include -I/opt/bitnami/common/include/sasl -I/opt/bitnami/common/include   -I/opt/bitnami/common/include -fPIC -I/bitnami/rubystack-linux-x64/output/ImageMagick/include/ImageMagick -I/bitnami/rubystack-linux-x64/output/ImageMagick/include/ImageMagick -O3 -I/opt/bitnami/common/include/ImageMagick -I/opt/bitnami/common/include -I/opt/bitnami/common/include/ImageMagick -I/opt/bitnami/common/include  -g -Wall -Wno-comment -m64  -c conftest.c"
conftest.c:3:26: fatal error: git2/version.h: Нет такого файла или каталога
 #include <git2/version.h>
                          ^
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <git2/version.h>
4: 
5: #if LIBGIT2_SOVERSION != 21
6: #error libgit2 version is not compatible
7: #endif
/* end */

**Comment by n-rodriguez** [comment]
This is the original command to install rugged (and the output) :

```
bitnami@redmine:~/apps/redmine/htdocs$ bundle install --without development test postgresql sqlite --deployment
Your Gemfile lists the gem redcarpet (~> 3.1.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching gem metadata from https://rubygems.org/.......
Using rake 10.4.2
...
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/bitnami/ruby/bin/ruby extconf.rb --use-system-libraries
checking for cmake... yes
checking for gmake... no
checking for make... yes
checking for pkg-config... yes
Building Rugged using system libraries.
libgit2 version is not compatible
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/bitnami/ruby/bin/ruby
	--use-system-libraries
	--with-git2-dir
	--without-git2-dir
	--with-git2-include
	--without-git2-include=${git2-dir}/include
	--with-git2-lib
	--without-git2-lib=${git2-dir}/
	--with-libgit2-config
	--without-libgit2-config
	--with-pkg-config
	--without-pkg-config


Gem files will remain installed in /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4 for inspection.
Results logged to /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged/gem_make.out
An error occurred while installing rugged (0.21.4), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.21.4'` succeeds before bundling.
```

**Comment by n-rodriguez** [comment]
Well, I've done some progress : I've compiled libgit2 itself in a separate dir and like @albertsun pkg-config is overriden by Bitnami. 

To work around this, I've copied libssh2.pc to Bitnami lib dir :
```
bitnami$ sudo cp /usr/lib/x86_64-linux-gnu/pkgconfig/libssh2.pc /opt/bitnami/common/lib/pkgconfig/
```

Then export PKG_CONFIG_PATH variable and build libgit2 :
```
bitnami@redmine:~/tmp/libgit2/build$ export PKG_CONFIG_PATH=/opt/bitnami/common/lib/pkgconfig
bitnami@redmine:~/tmp/libgit2/build$ pkg-config --print-errors --exists libssh2
bitnami@redmine:~/tmp/libgit2/build$ echo $?
0
bitnami@redmine:~/tmp/libgit2/build$ cmake ..
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1k") 
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- checking for module 'libssh2'
--   found libssh2, version 1.4.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ibestrest/tmp/libgit2/build
```
