### ISSUE TITLE
Clone with a port number

### ISSUE THREAD

**Issue by hntd187** [libgit2/rugged#396]
My git repo runs on a non-standard port, I've read most of the rugged code as well as googled around, is it intended that you cannot specify a port in someway? When I attempt to checkout via ssh with it I get an Early EOF, Rugged::NetworkError, which from searching around online seems to point to the URL scheme not being valid for Rugged, which is because of the port specification in the URL. Is there a work around for this or would I have to implement this myself?

**Comment by carlosmn** [comment]
libgi2 was indeed missing the particular way in which upload-pack reports certain kinds of errors. libgit2/libgit2#3137 sets its stderr to the server process' stderr output and returns a particular error code in these cases, which you can use to show a hint similar to git's, or your own.

**Comment by arthurschreiber** [comment]
Closing this as I think it was fixed by libgit2/libgit2#3137, and due to inactivity. Please let us know if you still face this issue!
