### ISSUE TITLE
`lookup': Object not found - failed to find pack entry () (Rugged::OdbError)

### ISSUE THREAD

**Issue by jatinganhotra** [libgit2/rugged#429]
Hi,

I am working on a script to get information about Git commits, where I am doing the following:

```
working_dir = `pwd`.chomp
rubygit_gem_repo = Git.open(working_dir, :log => Logger.new(STDOUT))
rugged_repo = Rugged::Repository.new(working_dir)
#Get the initial empty tree state
empty_tree=`git hash-object -t tree /dev/null`
empty_state = rugged_repo.lookup("#{empty_tree.chomp}")
```

The above line is where I get the following error:
/Users/silverSpoon/.rvm/gems/ruby-2.1.2/gems/rugged-0.21.0/lib/rugged/repository.rb:99:in `lookup': Object not found - failed to find pack entry (4b825dc642cb6eb9a060e54bf8d69288fbee4904) (Rugged::OdbError) from /Users/silverSpoon/.rvm/gems/ruby-2.1.2/gems/rugged-0.21.0/lib/rugged/repository.rb:99:in lookup from script.rb:24:in <main>`  

I tried the following, but everything looks correct:

```
bash-3.2$ git show 4b825dc642cb6eb9a060e54bf8d69288fbee4904
tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904

bash-3.2$ git fsck 4b825dc642cb6eb9a060e54bf8d69288fbee4904
Checking object directories: 100% (256/256), done.
```

What's wrong here? Regarding the empty_tree, I created that to look at the diff from nothing to the first commit. I found out the way to do that from this (StackOverflow answer)[http://stackoverflow.com/a/25064285/355722].

**Comment by roshan3133** [comment]
http://stackoverflow.com/questions/36546774/gitlab-repository-corrupted-showing-500-error-on-frontend/36599198#36599198
