### ISSUE TITLE
Rugged::Tree::Builder vs Rugged::Index

### ISSUE THREAD

**Issue by Fryguy** [libgit2/rugged#433]
This is more a question, but perhaps it's something for documentation.

So, we are trying to build commits in a bare repo.  Bare repos don't have an index, so we can't do `repo.index.stuff`.  However, we found that we can do either

``` ruby
index = Rugged::Index.new
index.read_tree(some_tree_we_want_to_change)
# manipulate tree
tree = index.write_tree(repo)
Rugged::Commit.create(repo, :tree => tree, ...)
```

or

``` ruby
tree_builder = Rugged::Tree::Builder.new(some_tree_we_want_to_change)
# manipulate tree
tree = tree_builder.write(repo)
Rugged::Commit.create(repo, :tree => tree, ...)
```

So, basically, they are nearly identical, except that index seems to have many more methods for manipulating and viewing the tree than the Rugged::Tree::Builder does.  So, the question is, why would I use a Rugged::Tree::Builder over a Rugged::Index?  Is there a reason to use (or _not_ use) one over the other for my task?

**Comment by ioquatix** [comment]
There is a hidden cost here.. `Rugged::Index` may need to read the entire tree, including all nested trees. This is O(N) where N = the number of things in the repository. This makes adding K discrete commits O(KN), i.e. exponential. It would be nice to have some clarification on this. Ideally, you can achieve the same with the tree builder in O(K) time, but it will depend on how you structure the repository.

**Comment by ioquatix** [comment]
So, just because I thought you might be interested, I found

http://www.rubydoc.info/gems/rugged/Rugged%2FTree:update

which allows you build up a list of changes, and then generate a new tree using the C api. Paths may contain slashes which is useful.
