### ISSUE TITLE
Backend installation/configuration

### ISSUE THREAD

**Issue by jamiehodge** [libgit2/rugged#434]
Would someone be so kind as to tell me how to install the mysql backend and configure rugged to use it? I've installed libgit2 using homebrew. Beyond that, I have done nothing out of the ordinary.

Any help would be very much appreciated.

Jamie

**Comment by arthurschreiber** [comment]
I guess this can be closed now? #410 was merged some time ago.

**Comment by arthurschreiber** [comment]
Closing this as #410 resolved this a while ago.
