### ISSUE TITLE
Compilation Fail 0.21.2 (GitLab dependency)

### ISSUE THREAD

**Issue by baptistedonaux** [libgit2/rugged#448]
$ gem install rugged -v '0.21.2'

Fetching: rugged-0.21.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
    ERROR: Failed to build gem native extension.

```
/usr/local/bin/ruby extconf.rb
```

checking for cmake... yes
checking for gmake... no
checking for make... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby
    --use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo' failed (RuntimeError)
    from extconf.rb:50:in`block (2 levels) in <main>'
    from extconf.rb:49:in `chdir'
    from extconf.rb:49:in`block in <main>'
    from extconf.rb:46:in `chdir'
    from extconf.rb:46:in`<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.1.0/gems/rugged-0.21.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/rugged-0.21.2/gem_make.out

**Comment by gon** [comment]
Deploying an application using Rugged gets stuck at the exact same point. @baptistedonaux did you ever find a solution to this?

**Comment by baptistedonaux** [comment]
Hi @gon I have resolved my problem. My fail came of my ruby version. I have re-complied my ruby and the problem has been resolved.

Actually, I run rugged via GitLab, with Ruby 2.1.5.

Isolate problem :)
