### ISSUE TITLE
Documentation with regard to command line

### ISSUE THREAD

**Issue by rubydesign** [libgit2/rugged#452]
Hi,
great stuff, wonderful to be able to just grab a repo and do stuff in ruby.

Alas, while having used git commandline for years, i find some of the conepts hard to understand.
Off course i appreciate that git works internally very very different from what a cmd user sees.
But since the lib exports that internal view, i find it hard (in places) to map that to what i know from the 
command line. Looking at stackoverflow i am not the only one.

So i will point out a few of these things. But since i am a newbie i may not be the best person to just go ahead and write something and send a pull. Rather i thought if someone from the team would want to take this on, we could start a private conversation and then together work on some rephrasing.
- Repository instantiation: unclear how it relates to the filesystem, specifically how actions on it reflect there.
- Repository writing: writing to it without file-name , what does that mean.
- Index section: talks about using Repository.index (that would be a class method?) but goes on to use Index.new . What does that affect. There is a reload, when or why would that be necessary and when do i write, concurrency ?
- basic file remove through rugged: took me way to long to figure out. Had to use remove_all, remove said something about not being staged. not documented at all as far as i saw.

Also a wiki page with a diagram and a basic writeup of the connections of the basic object would not hurt beginners. Again i would do this but lack the understanding, which is why i would like it to be there.

I am aware that this is all very basic stuff and if you feel i am just a dumbo nagging or you are too busy for this, just close and forget.

**Comment by arthurschreiber** [comment]
@dancinglightning Check https://github.com/libgit2/rugged/pull/294. I have to polish them up, but they should give you an idea how some of the cli concepts can be translated to the rugged API.

Otherwise, your concerns are valid. Rugged's documentation is probably not that helpful to someone that does not know the low-level git concepts too well. I'll see what I can do about that.

**Comment by dancinglightning** [comment]
well that was quick! and thanks

The examples sounds like a good idea, and those specific ones probably will help me later on.

I could proof-read, or try to help in other ways, just say how.
