### ISSUE TITLE
undefined method `lookup' for Rugged::Reference:Class

### ISSUE THREAD

**Issue by Zaiyong** [libgit2/rugged#455]
Hi all,

I'm running a open-source program based on ruby. The program uses Rugged::Reference.lookup which does not exist any more. I'm a new ruby user so i don't know how to fix this problem.
Could you please be so kind to help me with this issue? Is there any new function replacing lookup?

Best wishes,
Zaiyong

**Comment by arthurschreiber** [comment]
Hey @Zaiyong,

`Rugged::Reference.lookup` was removed, `repo.references[refname]` is the replacement for `Rugged::Reference.lookup`.

**Comment by Zaiyong** [comment]
Hi @arthurschreiber , it works. Tks!!
