### ISSUE TITLE
repository.status performs slow on solaris

### ISSUE THREAD

**Issue by giniedp** [libgit2/rugged#458]
In our current project Rugged works fine on OSX development machines. But when it comes to production it performs very slow using the same git repository and branch. A single call to 

    repository.status { |a, b| puts b }

takes over 20 seconds to complete.

The production machine is a SunOS 5.11 11.2 i86pc i386 i86pc Solaris
To install rugged on that machine we had to make the following change
https://github.com/sirlantis/rugged/commit/f642d3cded339d9db2f6bb00fe1659e29762c134

Does anyone has any idea why the status call might perform that bad? Any help and hint is appreciated.

**Comment by arthurschreiber** [comment]
This is probably not a rugged, but a libgit2 issue instead. As I don't have access to a Solaris machine, nor do I have any idea what the issue could be, I'd suggest you open an issue in the libgit2 issue tracker and link to this issue over there.

Anyway, which version of rugged are you using?

**Comment by giniedp** [comment]
i will open an issue there.
the rugged version is 0.21.0 and we will try to upgrade to the latest soon

**Comment by arthurschreiber** [comment]
There's been recently some new activity on the issue in the libgit2 issue tracker. As any fix will have to be made in libgit2 and will automatically be included in newer rugged releases, I'll close this issue for now.
