### ISSUE TITLE
Blob binary checking issue with files containing non-Latin strings

### ISSUE THREAD

**Issue by Freak613** [libgit2/rugged#465]
`Rugged::Blob.binary?` method recognizes files with non-Latin strings as binary file.

I've created script which stably reproduces the problem:
https://github.com/Freak613/rugged/blob/master/rugged.rb
As the result of script execution, I have following output:
```bash
tmp/rugged_test $ ruby rugged.rb
eng.txt binary?=false
rus.txt binary?=true
```

Here are binary representations of both created files:
```bash
/tmp/rugged_test master$ od -x eng.txt
0000000      6e65    6c67    7369    0068
0000007
/tmp/rugged_test master$ od -x rus.txt
0000000      80d1    83d1    81d1    81d1    bad0    b8d0    b9d0
0000016
```

This issue prevents using `binary?` method for searching text files in repository, with russian strings in my case.
Tested with `ruby (2.2.0p0)` and `rugged (0.21.4)`

**Comment by arthurschreiber** [comment]
`Rugged::Blob.binary?` is based on the binary detection functionality inside `libgit2`. I believe this was tweaked in more recent versions of `libgit2` (newer than 0.21.4), but I'm not a 100% sure. Anyway, if you commit these files to a repository using `git`, is the russian file treated as binary or as text?

**Comment by Freak613** [comment]
As I understand, russian file treated as text:
```bash
/tmp/rugged_test master$ git show 2832d55b21c64fc331ff3954c91b647da0e6d571
commit 2832d55b21c64fc331ff3954c91b647da0e6d571
Author: Test Author <testuser@github.com>
Date:   Tue Mar 10 00:39:29 2015 +0300

    Added rus.txt

diff --git a/rus.txt b/rus.txt
new file mode 100644
index 0000000..997a48e
--- /dev/null
+++ b/rus.txt
@@ -0,0 +1 @@
+русский
\ No newline at end of file
```

**Comment by arthurschreiber** [comment]
Can you check again with the latest rugged beta (`0.22.1b1`)?

**Comment by Freak613** [comment]
Tested. Problem persists.

**Comment by arthurschreiber** [comment]
Can you try again with the latest rugged beta? There were additional fixes made inside libgit2 which should have fixed this. I'm sorry that I can't check this myself right now.

**Comment by Freak613** [comment]
Currently, I'm getting this bug:
https://github.com/libgit2/rugged/issues/475
And didn't resolved it yet.

**Comment by arthurschreiber** [comment]
Hey @Freak613,

I'm looking through some of the open issues on rugged, and was wondering whether you got any update on this issue? Is this still a problem with rugged 0.23?

**Comment by Freak613** [comment]
Hi @arthurschreiber,
I've tested issue with 0.23.2 rugged version and it has been fixed. Thanks!

**Comment by arthurschreiber** [comment]
Cool! :+1: Thanks for letting me know.
