### ISSUE TITLE
how to create  a commit in subdir not in repo'root dir using treebuilder??

### ISSUE THREAD

**Issue by zouqilin** [libgit2/rugged#474]

**Comment by arthurschreiber** [comment]
You'll be better off using an index to create a new commit, instead of the treebuilder.

**Comment by zouqilin** [comment]
#files=>[{:path="a/b/test.c", :content=>"", :method=>":add|:update|:remove"}...]
      def create_commit(files, ref, author, committer, commit_message)
        begin
            index = repo.index
            index.read_tree(@repo.rev_parse(ref).tree) unless repo.empty?
            files.each{|file|
              file[:path] = file[:path][1..-1] if file[:path][0] == "/"
              e = index[file[:path]]
              case file[:method]
              when :add
                  index.add(:path=>file[:path], :oid=>repo.write(file[:content], :blob), :mode=>0100644)
              when :update
                if e
                  index.update(:path=>file[:path], :oid=>repo.write(file[:content], e[:type]), :mode=>e[:mode])
                else
                  index.update(:path=>file[:path], :oid=>repo.write(file[:content], :blob), :mode=>0100644)
                end
              when :remove
                if e
                  if e[:type] == :blob
                    index.remove(file[:path])
                  elsif e[:type] == :tree
                    index.removedir(file[:path])
                  end
                end
              end
            }

            author ||= committer if committer
            committer ||= author if author

            update_ref = "HEAD"
            update_ref = @repo.branches[ref].canonical_name unless @repo.empty?
            options = {}
            options[:tree] = index.write_tree(repo)
            options[:author] = author if author
            options[:committer] = committer if committer
            options[:message] = commit_message if commit_message
            options[:parents] = @repo.empty? ? [] : [@repo.branches[ref].target].compact
            options[:update_ref] = update_ref

            Rugged::Commit.create(@repo, options)
        rescue Exception => ex
           Gitlab::AppLogger.error "repository.rb, create_commit, path:#{path_with_namespace}, false, error=>#{ex.to_s}"
            return nil
        end
      end
