### ISSUE TITLE
Feature ssh not detected on OSX

### ISSUE THREAD

**Issue by rkoster** [libgit2/rugged#476]
Similar to https://github.com/libgit2/rugged/issues/430

Version: rugged-0.23.0b1
```
bundle exec irb
2.0.0-p481 :001 > require 'rugged'
 => true
2.0.0-p481 :002 > Rugged.features
 => [:threads, :https]
```

```
pkg-config --libs libssh2
-L/usr/local/Cellar/libssh2/1.5.0/lib -lssh2
```

**Comment by arthurschreiber** [comment]
Did you build rugged from source? Can you post the output of `mkmf.log`? Please put it into a gist and put the link to the gist here, as the `mkmf.log` output can be quite verbose.

**Comment by rkoster** [comment]
The `mkmf.log` files for `rugged-0.23.0b1`, `rugged-0.23.0b2` and `rugged-0.22.2` can be found [here](https://gist.github.com/rkoster/c6ec7dbf7886d718c45c). On all versions ssh support was not detected.

**Comment by arthurschreiber** [comment]
@carlosmn Looks like CMake can't find libssh2 :disappointed: Any idea what might be causing this?

**Comment by arthurschreiber** [comment]
Okay, I just checked on my machine, and it works fine on my machine:

```
$ pkg-config --libs libssh2
-L/usr/local/Cellar/libssh2/1.5.0/lib -lssh2
```

From my `mkmf.log`:

```
-- checking for module 'libssh2'
--   found libssh2, version 1.5.0
```

**Comment by carlosmn** [comment]
My first guess would be that your login shell has either a different `pkg-config` from the one which can be found on the system, or that you have set a search path there which the CMake-called `pkg-config` wouldn't see.

One way to make sure that libssh2 can be found using the "normal" paths is to run `brew link libssh2` which will make sure to create the right symlinks.

**Comment by rkoster** [comment]
@carlosmn thanks for the hint about maybe using a different `pkg-config`. I got it working by doing a `brew uninstall pkg-config && brew install pkg-config`.
