### ISSUE TITLE
hi, which ruby version is more suitable to run rugged

### ISSUE THREAD

**Issue by zouqilin** [libgit2/rugged#477]

**Comment by arthurschreiber** [comment]
We run travis builds for rugged on these Ruby versions:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - rbx-2

There is no single "most suitable version", everything newer than `1.9.3` will work. But you should be using the latest stable ruby version, just for all the other performance and memory related improvements you'll get.
