### ISSUE TITLE
release stable version with libgit2 v0.22 compatibility

### ISSUE THREAD

**Issue by ktdreyer** [libgit2/rugged#480]
Mind releasing a stable version of 0.22? It would be quite nice to have a stable version of the gem available on Rubygems that works with libgit2 v0.22, since that's what's shipping in Fedora 22.

**Comment by arthurschreiber** [comment]
You should be able to use `0.22.1b1`. The rugged versioning scheme is a bit messy, but that version should be as "stable" as rugged releases are. (GitHub is / was using it in production).

**Comment by ktdreyer** [comment]
Hi Arthur, I'm using 0.22.1b1 and it works well. This request is to release a stable version, without the "beta" name, so it's available from Rubygems.org via `gem fetch` without the `--pre` option.

**Comment by arthurschreiber** [comment]
I just release 0.22.2. Sorry for the delay!
