### ISSUE TITLE
SSH Key authentication question

### ISSUE THREAD

**Issue by mieciu** [libgit2/rugged#484]
Could you please tell me if this `Invalid credential type` error is due to lack of SSL support in libgit2? Is there any possible way to determine this?

Or maybe I'm doing something wrong in this code?
```
$ irb
2.1.1 :001 > require 'rugged'
 => true
2.1.1 :002 > creds = Rugged::Credentials::SshKey.new( publickey: File.expand_path("~/.ssh/id_rsa.pub"), privatekey: File.expand_path("~/.ssh/id_rsa"))
 => #<Rugged::Credentials::SshKey:0x0000010296f458 @username=nil, @publickey="/Users/p/.ssh/id_rsa.pub", @privatekey="/Users/p/.ssh/id_rsa", @passphrase=nil>
2.1.1 :003 > Rugged::Repository.clone_at 'https://github.com/my/my.git', './test', :credentials => creds
ArgumentError: Invalid credential type
	from (irb):3:in `clone_at'
	from (irb):3
	from /Users/phejman/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
```

**Comment by mieciu** [comment]
I have ssh support
```
2.1.1 :004 > Rugged.features
 => [:threads, :https, :ssh]
```

**Comment by carlosmn** [comment]
You can't authenticate over HTTP with SSH keys. If you'd like to use SSH, ask rugged to use SSH by specifying such a URL.

**Comment by arthurschreiber** [comment]
As pointed out by @carlosmn, you're using the wrong URL. The correct URL would've been `git@github.com/my/my.git`.

**Comment by mieciu** [comment]
Hey, thank you for the insight - unfortunately, it doesn't work either:
```
creds = Rugged::Credentials::SshKey.new(username: 'git', publickey: File.expand_path("~/.ssh/id_rsa.pub"), privatekey: File.expand_path("~/.ssh/id_rsa"))
Rugged::Repository.clone_at 'git@github.com:my/my.git',
                            './example_dir',
                            :credentials => creds
```

returns
```
in `clone_at': Failed to authenticate SSH session: Callback returned error (Rugged::SshError)
```

What is weird, that using the same keys I can clone the repo via rugged's `SshKeyFromAgent`

**Comment by mieciu** [comment]
Could you help me determining what cause the error here? Is there any additional debug I can add to rugged lib?

**Comment by carlosmn** [comment]
Are you providing the key's passphrase in the actual code you're running?

**Comment by mieciu** [comment]
@carlosmn thanks a lot, it made my day :smile: 

I'm also looking forward to submit you a PR with more verbose error handling here, as well as some examples in docs. Have a great day!

**Comment by arthurschreiber** [comment]
@mieciu That'd be awesome! :heart:
