### ISSUE TITLE
timeout failed when i used clone_at

### ISSUE THREAD

**Issue by zouqilin** [libgit2/rugged#485]
irb> timeout 1 do
Rugged::Repository::clone_at("https//github.com/libgit2/libgit2.git", "libgit2.git", :bare=>true)
end

there are no TimeoutError until clone ok

**Comment by arthurschreiber** [comment]
Rugged does not release the GVL of Ruby, so during the time the clone is executed there can be no other Ruby code running. Timeout is implemented by running a seperate ruby thread that throws an exception after some time. Even if Rugged would release the GVL during clone operations, the `TimeoutError` would leave it in an inconsistent state.

You could use the `:transfer_progress` callback and throw an exception in there after some specific amount of time has passed relative from the start of the clone operation. That'd cleanly abort the clone. But it's not a perfect solution, as a very slow network transfer might cause that this callback does not get called often/quickly enough to make this type of cancellation reliable.

I'd suggest you start a child process and use that to execute the clone operation. You could then cleanly kill that process and remove the target folder if the clone does not finish in time.

**Comment by zouqilin** [comment]
ok, thanks
