### ISSUE TITLE
"error authenticating" with ssh-agent credentials, but "git clone" works

### ISSUE THREAD

**Issue by leemhenson** [libgit2/rugged#487]
This works from the terminal:

```git clone git@bitbucket.org:account-name/repo-name.git```

This fails with ```error authenticating```:

```ruby
Rugged::Repository.clone_at(
  'git@bitbucket.org:account-name/repo-name.git', 
  '/tmp/somepath', 
  credentials: Rugged::Credentials::SshKeyFromAgent.new(username: 'git'))
```

Any ideas why that libgit2 might push that error message out? On another computer, for a different user, the same code works fine so it must be something environmental. We've restarted the machine, restarted ssh-agent etc.

**Comment by carlosmn** [comment]
Unfortunately the code which talks to the ssh agent does not offer a lot of information in the error messages. One possible cause for the failure is not being able to talk to the agent, but if git can, then it's probably not that. Another failure can be that the key isn't in the cache yet so we don't see it in the list. Or it can be that you have a lot of keys in your agent's list and we hit the server's limit on auth attempts for a single connection. This latest one would happen if you have the key set in your ssh config, such that ssh itself would know which key to use, but libgit2 would not.

**Comment by leemhenson** [comment]
I think this was fixed by removing and reinstall packages like openssh, openssl. Something must have got screwed up. It would be nice to get better feedback from libgit2 but I suppose this is an edge case.
