### ISSUE TITLE
Error when trying to install rugged

### ISSUE THREAD

**Issue by duser0** [libgit2/rugged#489]
Hey

I've been trying to install rugged for the last few days (Dandelion Deploy seems to have stopped working because of it)... I'm getting the following error though.

Please bear with me as not a backender at all. I have absolutely no idea how to fix it. I've tried reinstalling RVM, Ruby, Rails, Node, cmake, pkg-config... and nothing has worked. But the error persists!

----

gem install rugged
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
	ERROR: Failed to build gem native extension.

    /Users/J/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150608-27367-63fel0.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/J/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
	from extconf.rb:66:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/J/.rvm/gems/ruby-2.2.1/gems/rugged-0.22.2 for inspection.
Results logged to /Users/J/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/rugged-0.22.2/gem_make.out

**Comment by duser0** [comment]
Oh and the mkmf.log file contains the following...

--------------------------------------------------------------------------------------------------

find_executable: checking for gmake... -------------------- no

--------------------

find_executable: checking for make... -------------------- yes

--------------------

find_executable: checking for cmake... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

"cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles""
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:14 (PROJECT):
  The CMAKE_C_COMPILER:

    Error: /usr/bin/xcode-select returned unexpected error.

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/Users/J/.rvm/gems/ruby-2.2.1/gems/rugged-0.22.2/vendor/libgit2/build/CMakeFiles/CMakeOutput.log".
See also "/Users/J/.rvm/gems/ruby-2.2.1/gems/rugged-0.22.2/vendor/libgit2/build/CMakeFiles/CMakeError.log".

**Comment by arthurschreiber** [comment]
Hey @duser0, sorry for the trouble you've to go through installing rugged.

Which version of OS X are you running on?
Do you have the latest version of the XCode command line utilities (or XCode itself) installed?

**Comment by duser0** [comment]
Hey Arthur!

I was running Mac Lion 10.7.5 and XCode Version 2308...

I just updated to the latest possible XCode 4.6.3 and that fixed the problem!

(I could then install rugged, then dandelion and net-sftp and dandelion deploys again!)

Thank you for your time and help

**Comment by arthurschreiber** [comment]
No worries! :+1:

**Comment by tetsushiawano** [comment]
I had the same issue. Solved by installing  XCode command line utilities.
