### ISSUE TITLE
Rugged::SshError: username does not match previous request

### ISSUE THREAD

**Issue by blatyo** [libgit2/rugged#490]
I'm experiencing a baffling error when trying to push a tag. I've tried `SshKeyFromAgent` and `SshKey` credentials, which both return the same error. `UserPassword` produces a different error, presumably because the remote is a git url rather than http. Here is a transcript of me reproducing the error:

``` ruby
> pry                                                                               
1.9.3 (main)[0]> require 'rugged'
=> true
1.9.3 (main)[0]> ssh =  Rugged::Credentials::SshKeyFromAgent.new(username: 'blatyo')
=> #<Rugged::Credentials::SshKeyFromAgent:0x007fa091adc508 @username="blatyo">
1.9.3 (main)[0]> repo = Rugged::Repository.new('.')
=> #<Rugged::Repository:70163807919760 {path: "/Users/amadsen/code/hillary/.git/"}>
1.9.3 (main)[0]> remote = repo.remotes['origin']
=> #<Rugged::Remote:0x007fa091b433c0 @owner=#<Rugged::Repository:70163807919760 {path: "/Users/amadsen/code/hillary/.git/"}>>
1.9.3 (main)[0]> tag = repo.tags['barf']
=> #<Rugged::Tag:70163754524580 {name: "barf", target: #<Rugged::Commit:70163754537160 {message: "bump version\n", tree: #<Rugged::Tree:70163754536480 {oid: fc16fba084944f78d6b2105a6b1fc4566a98293c}>
  <".gitignore" d6f9be726e90d95292fb1377b7a4b5d46c9b97cd>
  <".rspec" 8c18f1abdd4147f400c02b45e57297449ae4bc43>
  <"Gemfile" f744f149ab46c3fcabcff5739cad4f66c3510374>
  <"LICENSE.txt" 4564bc9fe3ab4af1c4842962f4a8759124128f10>
  <"README.md" 964ed237013fd177cc57a31a883eaba6f8eee715>
  <"Rakefile" 809eb5616adcc0ebb78862099794489bd5b5b1a0>
  <"hillary.gemspec" 657dcd4b2f1dff00f9381e5964593bc0cc71935f>
  <"lib" 2896c979cbdb28e9884db1cfe36ac11c0e4e910b>
  <"spec" 9f95da2d9b53884b75ab41d3a788eace427d7981>
, parents: ["a6d85dad968d56b5c4bfb48be6098cfae85a0705"]}>}>
1.9.3 (main)[0]> remote.push([tag.canonical_name], credentials: ssh)
Rugged::SshError: username does not match previous request
from (pry):7:in `push'
```

**Comment by carlosmn** [comment]
As the error says, you passed in one username during the initial connection and then used a different one when you were asked to provide the credentials. Look at the URL you're pushing to, it likely says that the username is `git`, as is the case for almost every non-trivial Git hosting system. Specifying you'd like to authenticate with `blatyo` when you've already said you want to authenticate as `git` is not something ssh servers like.

**Comment by blatyo** [comment]
Thanks Carlos! It was indeed my issue that I needed to specify the username as `git` I was blanking on where the previous username was coming from. Since the username can be inferred from the URL, is there a reason that it is a required option for the credentials?

**Comment by blatyo** [comment]
As an alternative, would it make sense to default to `git` as the username for the SSH credentials and call it out as the default in the documentation? I'd be happy to put together a PR for that.

**Comment by carlosmn** [comment]
There is no default for ssh usernames, other than the current user which the ssh binary uses. What the username should be is completely up to the context in which each application runs, which is why rugged/libgtit2 cannot know what the right thing is. It is for that reason that we ask the application to specify exactly how they'd like to authenticate, lest we put the caller into a hole they can't dig out of.

As for the username being part of the credentials object, that's part of what we use to authenticate. There is no guarantee ever that we'll know the username from the URL.

**Comment by blatyo** [comment]
You implied in your original response that `git` was the username that people would need to specify. If that is the case, it seems reasonable to me that, that would be a default for the credential. If someone wanted something different, they could specify the username as they do now. I didn't mean to imply ssh had a default username, simply that most people will be using the same username. Having a default would make the library easier for the majority.

This is the type of change I'm talking about:
``` ruby
module Rugged
  module Credentials
    class SshKeyFromAgent
      def initialize(options)
        @username = options.fetch(:username, 'git')
      end

      def call(url, username_from_url, allowed_types)
        self
      end
    end
  end
end

**Comment by msardar** [comment]
I am experiencing the same error with node.js. When I print username inside credentials callback, I get "git" and then ultimately it gives me "Error: username does not match previous request"
My clone URL is : "git@csgrad06.nwmissouri.edu:F2017-4450.ADB/msardar_gitlabClone.git"
`var opts = {
    fetchOpts: {
      callbacks: {
        certificateCheck: function () {
          return 1;
        },
        credentials: function (cloneURL, userName) {
          var userNameExplicit = "msardar";
          console.log("***************" + userNameExplicit)
          return Git.Cred.sshKeyNew(
            userNameExplicit,
            sshPublicKeyPath,
            sshPrivateKeyPath,
            "empty");
        }
      }
    }
  };`

I know the issue posted is in Rugged, but I just wanted to know the underlying logical error, is it taking the username from my URL and I cannot set it explicitly?

**Comment by carlosmn** [comment]
@msardar your username to use GitHub via ssh is `git` _just like the URL says_. Trying to authenticate as `msardar` is not going to work.
