### ISSUE TITLE
Rugged::Remote missing url= method

### ISSUE THREAD

**Issue by joeyfreund** [libgit2/rugged#505]
Just updated from `0.22.2` to `0.23.0`, and now I get

```
undefined method `url=' for #<Rugged::Remote:0x007fc240be9420> (NoMethodError)
```

_Note:_ Downgrading to 0.22.2 solved the problem.

**Comment by carlosmn** [comment]
It's not missing, it was removed, as detailed in the [CHANGELOG](https://github.com/libgit2/rugged/blob/master/CHANGELOG.md), since it was a really bad idea to have it there.

**Comment by joeyfreund** [comment]
Oops, I totally missed it.
Thanks. 
Hope you don't mind me closing this issue.
