### ISSUE TITLE
undefined reference to WinHttpReadData

### ISSUE THREAD

**Issue by jweather** [libgit2/rugged#506]
Building master on Windows Server 2012 64-bit with MSVC 2013, Ruby 2.1.6, DevKit, and CMake 3.3.0:

`C:/Users/Administrator/Desktop/spi2/app/server/native/windows/bin/ruby.exe extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=C:/
 -- C:\Users\Administrator\Desktop\devkit\bin/make.exe
checking for main() in -lgit2... yes
checking for git2.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating rugged-i386-mingw32.def
compiling rugged.c
compiling rugged_backend.c
compiling rugged_blame.c
compiling rugged_blob.c
compiling rugged_branch.c
compiling rugged_branch_collection.c
compiling rugged_commit.c
compiling rugged_config.c
compiling rugged_cred.c
compiling rugged_diff.c
compiling rugged_diff_delta.c
compiling rugged_diff_hunk.c
compiling rugged_diff_line.c
compiling rugged_index.c
compiling rugged_note.c
compiling rugged_object.c
compiling rugged_patch.c
compiling rugged_reference.c
compiling rugged_reference_collection.c
compiling rugged_remote.c
compiling rugged_remote_collection.c
compiling rugged_repo.c
compiling rugged_revwalk.c
compiling rugged_settings.c
compiling rugged_signature.c
compiling rugged_submodule.c
compiling rugged_submodule_collection.c
compiling rugged_tag.c
compiling rugged_tag_collection.c
compiling rugged_tree.c
linking shared-object rugged/rugged.so
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_close':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:261: undefined reference to `WinHttpCloseHandle@4'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `write_chunk':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:498: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:509: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:517: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `apply_basic_credential':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:114: undefined reference to `WinHttpAddRequestHeaders@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_connect':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:294: undefined reference to `WinHttpOpenRequest@28'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:308: undefined reference to `WinHttpSetTimeouts@20'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:338: undefined reference to `WinHttpSetOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:353: undefined reference to `WinHttpSetOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:364: undefined reference to `WinHttpSetOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:370: undefined reference to `WinHttpAddRequestHeaders@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:388: undefined reference to `WinHttpAddRequestHeaders@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:405: undefined reference to `WinHttpAddRequestHeaders@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `apply_default_credentials':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:148: undefined reference to `WinHttpSetOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_close_connection':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:532: undefined reference to `WinHttpCloseHandle@4'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:541: undefined reference to `WinHttpCloseHandle@4'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_connect':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:576: undefined reference to `WinHttpOpen@20'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:588: undefined reference to `WinHttpSetTimeouts@20'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:595: undefined reference to `WinHttpConnect@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `do_send_request':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:627: undefined reference to `WinHttpSendRequest@28'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `send_request':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:669: undefined reference to `WinHttpSetOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `certificate_check':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:225: undefined reference to `WinHttpQueryOption@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:235: undefined reference to `_imp__CertFreeCertificateContext@4'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_write_chunked':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:1106: undefined reference to `WinHttpAddRequestHeaders@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_write_single':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:979: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `put_uuid_string':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:995: undefined reference to `_imp__UuidCreate@4'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_read':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:727: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:777: undefined reference to `WinHttpReceiveResponse@8'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:785: undefined reference to `WinHttpQueryHeaders@24'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `parse_unauthorized_response':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:468: undefined reference to `WinHttpQueryAuthSchemes@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_read':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:759: undefined reference to `WinHttpWriteData@16'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:813: undefined reference to `WinHttpQueryHeaders@24'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:827: undefined reference to `WinHttpQueryHeaders@24'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:925: undefined reference to `WinHttpQueryHeaders@24'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `fallback_cred_acquire_cb':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:177: undefined reference to `_imp__CoInitializeEx@8'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:181: undefined reference to `_imp__CoCreateInstance@20'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:201: undefined reference to `_imp__CoUninitialize@0'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:201: undefined reference to `_imp__CoUninitialize@0'
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/ext/rugged/../../vendor/libgit2/build/libgit2.a(winhttp.c.obj): In function `winhttp_stream_read':
C:/Users/Administrator/Desktop/spi2/app/server/native/windows/lib/ruby/gems/2.1.0/gems/rugged-0.23.0/vendor/libgit2/src/transports/winhttp.c:942: undefined reference to `WinHttpReadData@16'
collect2.exe: error: ld returned 1 exit status
make: *** [rugged.so] Error 1

make failed, exit code 2
`

I can work around it by adding -DWINHTTP=OFF to the cmake line in extconf.rb.  What am I missing here?

**Comment by arthurschreiber** [comment]
You're missing nothing. :smile: 

Since libgit2 0.23, libgit2 tries to use the winhttp library even when being compiled with the mingw build tools. By default, rugged builds a static version of the libgit2 binary, but winhttp is not part of that static binary. There's a winhttp.a file generated by the libgit2 build, and I think you could link to it to fix this issue. Or you use the `-DWINHTTP=OFF` workaround.

**Comment by jweather** [comment]
So it's normal to not be able to "gem install rugged" out of the box?

**Comment by arthurschreiber** [comment]
On windows, yes, sort of. We never officially supported rugged on windows, and I tried multiple times to bring us official win32 support, but there's always been some weirdness that blocked these efforts.

May I ask what you're trying to use rugged for on win32? Seeing that people are actually using rugged on win32 might make me reconsider spending the necessary time. :)

**Comment by jweather** [comment]
https://github.com/samaaron/sonic-pi

We use git on the backend to save the workspace files to allow for
recovering old versions.

On Thu, Aug 6, 2015 at 1:01 PM, Arthur Schreiber <notifications@github.com>
wrote:

> On windows, yes, sort of. We never officially supported rugged on windows,
> and I tried multiple times to bring us official win32 support, but there's
> always been some weirdness that blocked these efforts.
>
> May I ask what you're trying to use rugged for on win32? Seeing that
> people are actually using rugged on win32 might make me reconsider spending
> the necessary time. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgit2/rugged/issues/506#issuecomment-128443998>.
>



-- 
Jeremy Weatherford

**Comment by samaaron** [comment]
I'd love to see more love directed towards rugged on Windows. I've been trying to get it running over there with not much luck. I get lock issues when attempting to open up a existing repo and segfaults when I try and init a new repo. This is after having to tweak `extconf.rb` by adding these flags to this line:

https://github.com/libgit2/rugged/blob/master/ext/rugged/extconf.rb#L66

````
-DCMAKE_INSTALL_PREFIX=C:/ -DWINHTTP=OFF
```

**Comment by arthurschreiber** [comment]
@samaaron That's where I was as well, and then I got fed up and just kicked windows out. There's something really weird going on with libgit2 and the mingw version that is used by the windows devkit and it causes a ton of segfaults and many other funny failures.

@carlosmn Any idea what's going on here?

**Comment by carlosmn** [comment]
If it's due to crashes I would expect it to come from using the wrong calling convention, or (related) possibly the wrong compiler being  detected. Having to turn off WinHTTP does point to this as well, since the build system detects when we're on mingw and uses the def fie in that case.

As far as I know, ruby does make you use mingw, so the MSVC version is irrelevant. Unless libgit2's build system does somehow manage to find it, in which case it just means it messed up.

I don't think I've ever tried to build ruby or gems on Windows; but I might be able to try some things out in between compiles and deploys.

**Comment by arthurschreiber** [comment]
@jweather & @samaaron I just merged #554, so you should be able to build on windows now, provided you have the Windows DevKit installed and have CMake in your `PATH`. Running the tests on windows won't really work yet, but that's unrelated, rugged itself should be working just fine.

**Comment by samaaron** [comment]
Happy days! Thanks :-)
