### ISSUE TITLE
Update ref race condition

### ISSUE THREAD

**Issue by mkanoor** [libgit2/rugged#511]
Does Rugged::Commit's :update_ref work when 2 rugged instances are working on the same bare repository. 1 rugged instance would want its commit to update the ref, while the other one would want its commit to update the ref. This could also happen if someone was interacting with the same repo using command line git. When a ref is being updated does libgit2 use the lock file in .git/index.lock which would be consistent with the file that the command line git locks when pushing a commit.

**Comment by arthurschreiber** [comment]
Yes, update_ref should correctly handle race conditions. :smile:

**Comment by arthurschreiber** [comment]
Actually, it's not that easy. You need to specify the revision you expect the ref to be at as part of the ref update. Otherwise we can't ensure consistency.

This has nothing to do with the `.git/index.lock` file.

**Comment by arthurschreiber** [comment]
Here's how it works: The list of parents that you specify as `:parents` to `Commit.create` needs to contain the tip of that the ref you pass in `:update_ref`. If they don't match, `.create` will fail.

**Comment by mkanoor** [comment]
Thanks @arthurschreiber. Closing issue
