### ISSUE TITLE
Unable to create new, empty repository

### ISSUE THREAD

**Issue by tpickett66** [libgit2/rugged#522]
According to the README I should be able to init a new repo at an arbitrary path but I keep getting an error.

### From the README
>You can create a new repository with init_at. Add a second parameter :bare to make a bare repository:

>`Rugged::Repository.init_at('.', :bare)`

### My Code:
```ruby
require 'rugged'
repo_path = File.expand_path('~/Desktop/foo')
Dir.mkdir(repo_path)
repo = Rugged::Repo.init_at(repo_path, :bare) # => Rugged::RepositoryError: Path is not a repository: /Users/tpickett/Desktop/foo/
```
Am I just misunderstanding the documentation in that this doesn't actually `init` a new repo in the git cli sense but just builds a new object pointing at that repo?

**Comment by tpickett66** [comment]
Oh, I guess I should have mentioned that I'm using the gem directly from github master.

**Comment by arthurschreiber** [comment]
Are you the snippet you posted is what you're trying to execute? There is no `Rugged::Repo`.

```
Arthurs-iMac:rugged arthur$ bin/rake console
[rugged] main> repo_path = File.expand_path('~/Desktop/foo')
=> "/Users/arthur/Desktop/foo"
[rugged] main> Dir.mkdir(repo_path)
=> 0
[rugged] main> repo = Rugged::Repository.init_at(repo_path, :bare)
=> #<Rugged::Repository:70127135810640 {path: "/Users/arthur/Desktop/foo/"}>
```

**Comment by tpickett66** [comment]
When transcribing into github I didn't type it out right, I guess I should have copy/pasted, and when I copied your example it worked. Thanks!
