### ISSUE TITLE
Unable to init a repository with alternate backend

### ISSUE THREAD

**Issue by tpickett66** [libgit2/rugged#523]
Looking at the README I should be able to use a backend other than a filesystem for rugged. I'm starting down the path of developing one such backend and can't get a repository to init.

Using the gem installed directly from github the following code produces a type error that I can't seem to track down in either the rugged or libgit2 source.
```ruby
require 'rugged'
require 'pry'

class MyBackend < Rugged::Backend
  def method_missing(method_name, *args, &block)
    binding.pry
    super
  end
end

fake_backend = MyBackend.new

repo = Rugged::Repository.bare('bar', backend: fake_backend)
```
```
TypeError: wrong argument type MyBackend (expected Data)
	from (irb):10:in `bare'
	from (irb):10
```

When I pass in a random object I get the expected `Rugged::Error: Backend must be an instance of Rugged::Backend`, but even passing in a `Rugged::Backend` without subclassing it doesn't work. Any pointers as to where I'm going wrong would be fantastic.

**Comment by arthurschreiber** [comment]
Rugged backends have to be implemented in C. The `Rugged::Backend` class is only meant as a wrapper for a `rugged_backend` struct in C.

You can check https://github.com/redbadger/rugged-redis to see an example redis based backend.

Please note that custom backends are experimental, none of the main maintainers of rugged actually use them.

**Comment by tpickett66** [comment]
That makes sense, thanks.
