### ISSUE TITLE
Finding commit oid and path from tree/blob

### ISSUE THREAD

**Issue by sonalkr132** [libgit2/rugged#541]
Suppose, I have a tree object
```Ruby
tree = repo.lookup "1a3dbf1f4e653778b2d0e0857a00c49fd9ca0a22" #sha/oid of tree
```
Is it possible that I can find the commit which wrote this tree and its path (relative to root of repo)? I couldn't find anything in documentation.

**Comment by arthurschreiber** [comment]
Hey @sonalkr132! What do you mean by "wrote this tree"? A tree can be associated to different commits, and there is no way to find out which commit created this tree first.

I suppose you could loop through all commits and then recursively loop for all trees referenced by every commit and search for the tree, but that's going to be very slow.

**Comment by sonalkr132** [comment]
> What do you mean by "wrote this tree"?

If I write/update a blob in a tree, then the sha/oid of the tree will be updated. At the same time a commit will be added to the repo. I want to find out that commit. You are right, probably there is no good way to do.
Is it possible that I can find path(relative to root) of a tree/blob? If I have the commit and the oid of tree/blob, I suppose I can do a walk. I was wondering if I can do better than that.

**Comment by arthurschreiber** [comment]
I think your understanding of the git data structures is not quite right. :smile: 

If you write a commit that changes some files, a new tree gets created, not the other way around. This tree either references other trees (for subfolders) or blobs. These blobs and trees get reused across different commits if they are equal.

If you have a tree or blob, you can do the following:

Create a `Rugged::Walker` with the sort order that satisfies your requirements. Most likely, this will be `Rugged::SORT_DATE|Rugged::SORT_TOPO`. Then you need to go through each commit and check it's trees recusively to see whether the tree/blob you're searching for is contained inside that commit. That should let you find the commit that initially introduced a tree/blob.

**Comment by sonalkr132** [comment]
> I think your understanding of the git data structures is not quite right

Sorry, I am getting there.

Thanks for you help :yellow_heart:

**Comment by arthurschreiber** [comment]
No worries mate. If you got any more questions or run into issues with rugged itself, feel free to ask here or on StackOverflow (preferred). :)
