### ISSUE TITLE
index.diff diffs against working directory instead of index/staging

### ISSUE THREAD

**Issue by mmozuras** [libgit2/rugged#548]
From README:

```ruby
# Diff between index/staging and current working directory
diff_index = repository.index.diff
```

But in reality, it only diffs against working directory and doesn't include changes from index/staging. Tested with `~> 0.23.0`.

Related issue in [Pronto](https://github.com/mmozuras/pronto): https://github.com/mmozuras/pronto/issues/111

**Comment by ethomson** [comment]
That issue seems to suggest that this is working properly: a diff between the index and the working directory *should* show no changes when the index matches the working directory.  When the user does a reset, the diff shows (correctly) the changes in the working directory that have not been staged.

Do you want to diff against `HEAD`?

**Comment by mmozuras** [comment]
@ethomson oh, I misunderstood then. What would you use to achieve `git diff --staged`?

**Comment by ethomson** [comment]
I believe that you want:

    # Diff between index/staging and another diffable (commit/tree/index)
    diff_index_diffable = repository.index.diff(some_diffable)

In this case:  `repository.index.diff(repository.head)`

**Comment by mmozuras** [comment]
@ethomson nope, that's not it.

<img width="696" alt="screenshot 2015-11-18 21 08 14" src="https://cloud.githubusercontent.com/assets/54526/11251125/8056a0c6-8e38-11e5-8732-1b9bdf6727e3.png">

What's also confusing for me personally:

```ruby
repo.index.entries # lists all files in the repository instead of only the ones in index/staging
```

What am I misunderstanding?

**Comment by ethomson** [comment]
Hmm.  I'm sorry to say that I may be misunderstanding also.  Hopefully @arthurschreiber can come to our rescue?

**Comment by carlosmn** [comment]
That is the correct function. Unfortunately it seems not to behave correctly when you give it a commit. If you pass the tree, as in

    repo.index.diff(repo.head.target.tree)

you'll see the changes.

**Comment by mmozuras** [comment]
@carlosmn @ethomson thanks, that answers my initial question :bow:.

**Comment by ethomson** [comment]
To your second question, the index is not a diff, it's the list of files that are going to be committed.  And a commit is a snapshot (again, not a diff).

So if you enumerate the index, you're enumerating all the files that are about to be committed.  `git status` shows you the diff of the HEAD to the index (staged changes) and the index to the workdir (unstaged changes).

So it's by-design that `repo.index.entries` lists all the files in the repository.

**Comment by mmozuras** [comment]
It's starting to all come back to me... Have to go through some of those `git` books again :smile: 

@ethomson thanks for your help and patience! :smile:
