### ISSUE TITLE
how to get "git ls-tree -r master" via Rugged?

### ISSUE THREAD

**Issue by zotherstupidguy** [libgit2/rugged#555]

**Comment by arthurschreiber** [comment]
Hey @zotherstupidguy,

here's some Rugged code that will roughly do what `git ls-tree -r master` returns:

```ruby
repo = Rugged::Repository.new "."
tree = repo.branches["master"].target.tree
tree.walk(:postorder) do |root, entry|
  if entry[:type] != :tree
    puts "%o %s %s %s" % [entry[:filemode], entry[:type], entry[:oid], "#{root}#{entry[:name]}"]
  end
end
```

In the future, please refrain from asking questions on the Rugged issue tracker, and instead post your question on StackOverflow and tag it with "libgit2" and "rugged".

Happy Holidays!

**Comment by zotherstupidguy** [comment]
@arthurschreiber  THANK YOU!! :+1: :+1: :+1:
