### ISSUE TITLE
Rugged has been compiled without support for ssh

### ISSUE THREAD

**Issue by sysadmiral** [libgit2/rugged#579]
Hi,

Trying to get some help with rugged/libgit.

I have a clean Debian Jessie install and I am installing r10k (https://github.com/puppetlabs/r10k).

It requires rugged/libgit but no matter what I do I cannot get it to compile with SSH.

High level steps to reproduce:

Install Debian Jessie (no packages selected at tasksel)
Install cmake make pkg-config libssh2-1-dev
Install puppet repo and puppet-agent
/opt/puppetlabs/puppet/bin/gem install rugged

But when I try to use r10k it throws a warning:

```
WARN	 -> Rugged has been compiled without support for ssh; Git repositories will not be reachable via ssh.
WARN	 -> Rugged has been compiled without support for https; Git repositories will not be reachable via https.
```

Is there something very obvious that I am doing wrong here?

**Comment by arthurschreiber** [comment]
No, the steps you mentioned should be working just fine for installing rugged with ssh support. Can you find the `mkmf.log` file that was generated when you installed `rugged` and paste it's contents into a gist?

**Comment by sysadmiral** [comment]
Here you go: https://gist.github.com/sysadmiral/75ae3b9ae734a6502471

**Comment by arthurschreiber** [comment]
This is weird. From the output, you can see that libgit2 is being linked against libssh2.

@carlosmn Any idea what's going on?

**Comment by sysadmiral** [comment]
Hi after reverting my system to post OS install and running throught the steps again it has worked compiling SSH support.

Previously I had installed OS > Installed rugged > get failures > install dependencies > reinstall rugged > get failures.

Installing dependencies BEFORE installing rugged works. It looks like reinstalling rugged has some issue but I'm not sure if that is a rubygems issue or a rugged issue or something else! :smile:

**Comment by arthurschreiber** [comment]
This is most likely some issue with leftover configuration from the installation attempt without the dependencies in place. Glad you're able to get everything working in the end!
