### ISSUE TITLE
Unexpected blob encoding returned

### ISSUE THREAD

**Issue by bartj3** [libgit2/rugged#588]
When searching through [the issues related to encoding](https://github.com/libgit2/rugged/issues?utf8=✓&q=encoding) it seems like UTF-8 is the expected commit message encoding. However for blobs I keep getting ASCII strings back when using Rugged. Is this a bug or expected behaviour?

```ruby
require 'rugged'

repo = Rugged::Repository.new '.'
original_data = "an example string"
builder = Rugged::Tree::Builder.new(repo)
builder.insert name: 'example', oid: repo.write(original_data, :blob), type: :blob, filemode: 0100644
tree = builder.write
stored_data = repo.read(repo.lookup(tree).first[:oid]).data

puts original_data.encoding    # => UTF-8
puts stored_data.encoding      # => ASCII-8BIT

puts Encoding.default_external # => UTF-8
puts Rugged::VERSION           # => 0.24.0
puts RUBY_VERSION              # => 2.2.1
```

**Comment by vmg** [comment]
Hey @bartj3! This is definitely intended. Commit objects may contain (optionally) a header line specifying their encoding *for the commit message*, so in some situations we may be able to lookup that encoding when returning the commit message to Ruby.

Blobs on the other hand are... well... They're blobs. Raw binary data with the contents of a file. Unfortunately there's no place in Git to store the encoding for a blob (this is a limitation in the design of the VCS), so we need to return the contents of the blob tagged with Ruby's default "binary encoding" (which is ASCII-8bit).

Your best bet to work around this limitation in Git is using encoding detection heuristics. We wrote a gem that does just that and we use it reliably on production at GitHub.com: https://github.com/brianmario/charlock_holmes

I hope that's of use to you. Thank you!

**Comment by bartj3** [comment]
Aaah, makes sense! Thanks for taking the time to explain it to me!
