### ISSUE TITLE
Update libgit2 to 0.24.1

### ISSUE THREAD

**Issue by connorshea** [libgit2/rugged#593]
Maintenance release, includes bug fixes and such: https://github.com/libgit2/libgit2/releases/tag/v0.24.1

**Comment by sschuberth** [comment]
libgit2's `v0.24.1` tag is not on its `master` branch but on the `maint/v0.24` branch. rugged's `master` on the other hand is currently using commit `9068704` from libgit2's `master`. So I guess there's no way to make rugged use libgit2's `v0.24.1` tag as rugged probably depends on more recent features from libgit's `master` branch.

**Comment by ethomson** [comment]
@sschuberth is correct - rugged does not track a released version of libgit2, but tracks master instead, so it gets live goodness as it happens.  All those bug fixes in libgit2 0.24.1 were backported out of master, so we'll get them in Rugged as soon as we update to a newer libgit2 master snapshot (if they're not here already!)

**Comment by connorshea** [comment]
This can probably be closed, then. Apologies for the misunderstanding.

**Comment by ethomson** [comment]
No apologies necessary!

**Comment by arthurschreiber** [comment]
Actually, we sometimes release point versions tracking libgit2 versions,
but these mainly depend on the bandwidth available to maintainers.

In general, rugged betas are really stable and if you depend on the latest
developments in libgit2, we recommend you use those.
Connor Shea <notifications@github.com> schrieb am Mi., 27. Apr. 2016 um
23:22:
