### ISSUE TITLE
v0.25.0b2 tag in Git is wrong

### ISSUE THREAD

**Issue by sschuberth** [libgit2/rugged#598]
I was wondering why Gem version 0.25.0b2 does not include PR #589, and looking deeper into it it turns out that tag `v0.25.0b2` points to 85520387f27889c88117fc3473a7824a66901f53, which is the tip of the `arthur/prepare-v0.25.0b2` branch. I believe this to be wrong. Instead, the tag should point to the commit on `master` that merges `arthur/prepare-v0.25.0b2`, see PR #597.

**Comment by carlosmn** [comment]
This is in purpose in order to get b2 out without the libgit2 changes which include a large refactoring of the iterator code. Once that's validated b3 will eventually come out including an update to libgit2.

**Comment by arthurschreiber** [comment]
@carlosmn is right. Sorry for the confusion! We will push a b3 release including all the latest libgit2 and rugged changes once the refactored iterator code was put through more testing.
