### ISSUE TITLE
Repo does not seem to be properly closed after accessing it

### ISSUE THREAD

**Issue by sschuberth** [libgit2/rugged#601]
I'm using v0.25.0b2 on Windows. I noticed that something like

    path = 'path/to/repository'
    repository = Rugged::Repository.new(path)
    commit = repository.last_commit
    FileUtils.rm_r(path)

fails with

    `rmdir': Directory not empty @ dir_s_rmdir - path/to/repository (Errno::ENOTEMPTY)

Of course the given "not empty" reason is bogus as `FileUtils.rm_r()` is supposed to be able to delete non-empty directories. I can make it work by omitting the `commit = repository.last_commit` line, so I assume code triggered by `last_commit` is not closing a file descriptor to the `.git` directory correctly.

**Comment by vmg** [comment]
Hi @sschuberth! Since Ruby is a dynamic language, you will need to manually close the repository object to release the file descriptors for the different components of the repo.

See: https://github.com/libgit2/rugged/blob/master/ext/rugged/rugged_repo.c#L1748-L1757

Thanks!
