### ISSUE TITLE
v0.25.0b3 stopped to build on Windows

### ISSUE THREAD

**Issue by sschuberth** [libgit2/rugged#612]
While v0.25.0b2 was building ok, with v0.25.0b3 I get

    linking shared-object rugged/rugged.so
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(filebuf.c.obj): In function `write_deflate':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/filebuf.c:176: undefined reference to `deflate'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(filebuf.c.obj): In function `git_filebuf_cleanup':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/filebuf.c:123: undefined reference to `deflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(filebuf.c.obj): In function `git_filebuf_open_withsize':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/filebuf.c:318: undefined reference to `deflateInit_'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(zstream.c.obj): In function `git_zstream_init':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:33: undefined reference to `deflateInit_'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(zstream.c.obj): In function `git_zstream_reset':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:44: undefined reference to `deflateReset'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(zstream.c.obj): In function `git_zstream_get_output':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:100: undefined reference to `deflate'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:100: undefined reference to `deflate'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(zstream.c.obj): In function `git_zstream_free':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:39: undefined reference to `deflateEnd'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/zstream.c:39: undefined reference to `deflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(odb_loose.c.obj): In function `finish_inflate':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:212: undefined reference to `inflate'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:214: undefined reference to `inflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(odb_loose.c.obj): In function `read_header_loose':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:444: undefined reference to `inflateInit_'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:449: undefined reference to `inflate'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(odb_loose.c.obj): In function `start_inflate':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:201: undefined reference to `inflateInit_'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:204: undefined reference to `inflate'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(odb_loose.c.obj): In function `inflate_tail':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:292: undefined reference to `inflateEnd'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:277: undefined reference to `inflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(odb_loose.c.obj): In function `inflate_buffer':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:245: undefined reference to `inflateInit_'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:251: undefined reference to `inflate'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/odb_loose.c:253: undefined reference to `inflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(pack.c.obj): In function `packfile_unpack_compressed':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:869: undefined reference to `inflateInit_'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:880: undefined reference to `inflate'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:895: undefined reference to `inflateEnd'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:887: undefined reference to `inflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(pack.c.obj): In function `git_packfile_stream_open':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:792: undefined reference to `inflateInit_'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(pack.c.obj): In function `git_packfile_stream_read':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:818: undefined reference to `inflate'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(pack.c.obj): In function `git_packfile_stream_free':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:843: undefined reference to `inflateEnd'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/pack.c:843: undefined reference to `inflateEnd'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(indexer.c.obj): In function `crc_object':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:246: undefined reference to `crc32'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:253: undefined reference to `crc32'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(indexer.c.obj): In function `hash_and_save':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:388: undefined reference to `crc32'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(indexer.c.obj): In function `inject_object':
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:706: undefined reference to `crc32'
    c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:714: undefined reference to `crc32'
    C:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/ext/rugged/../../vendor/libgit2/build/libgit2.a(indexer.c.obj):c:/Ruby/lib/ruby/gems/2.3.0/gems/rugged-0.25.0b3/vendor/libgit2/src/indexer.c:724: more undefined references to `crc32' follow
    collect2.exe: error: ld returned 1 exit status
    make: *** [rugged.so] Error 1

    make failed, exit code 2

**Comment by sschuberth** [comment]
@carlosmn Could this be related to your commit https://github.com/libgit2/libgit2/commit/b1093e62d521b2625f1651a3c2083a0c3e92ffad as Ruby-DevKit on Windows always is 32-bit?

**Comment by arthurschreiber** [comment]
@sschuberth I don't think so. wingw64 exists in 32 and 64 bit versions. The naming is unfortunately a bit confusing.

**Comment by sschuberth** [comment]
@arthurschreiber Any other idea what might cause the issue? I briefly looked at the changes between v0.25.0b2 and v0.25.0b3 but did not find anything striking.

**Comment by carlosmn** [comment]
It _shouldn't_ be related. We just dropped support for mingw32. mingw64 (which IIUC is what ruby uses) should not be affected. If it is, that'd be a bug in some part of the build system. That change should also only end up affecting the CI builds.

It looks like the zlib code is not being included into `libgit2.a`. Did we change something else which tells us what to use for linking? A change in order, or maybe CMake detecting zlib in the system but us not linking to it would also explain this.

**Comment by svmastersamurai** [comment]
Adding in the zlib library to `extconf.rb` got it working for me again: https://github.com/svmastersamurai/rugged/commit/d81611c333c149ab10d7ed08e0497c0b19b0e4be

**Comment by sschuberth** [comment]
@svmastersamurai Thanks. But the obvious question is: What change made this necessary?

**Comment by arthurschreiber** [comment]
We no longer use pkg-config on windows, so these settings need to be set
manually now. Looks like we missed the option for zlib.
Sebastian Schuberth <notifications@github.com> schrieb am Mo., 12. Sep.
2016 um 07:12:

**Comment by sschuberth** [comment]
@arthurschreiber Are you going to handle that (by cherry-picking @svmastersamurai's commit to maintain credits), or do you want any of us to file a PR?

**Comment by sschuberth** [comment]
@arthurschreiber Any update on this?

**Comment by arthurschreiber** [comment]
I'm traveling currently, but should have time for this next week. If you'd
like to see this changed earlier, feel free to open a PR and I'll merge it
asap.
