### ISSUE TITLE
Question: git repositories in memory?

### ISSUE THREAD

**Issue by birdoftheday** [libgit2/rugged#635]
I was wondering if there is any way to create a git repository in memory before writing it to a directory. I am currently creating a flash card application where users can create decks which act like Git repositories. The output format is a gzipped directory containing the repository. Because no repository is actually written to a directory on disk, and also because a user might abandon their work before saving it, it would be helpful to have some way of creating them without having to write them anywhere. Is this possible? Thank you.

**Comment by birdoftheday** [comment]
Fixed.

**Comment by birdoftheday** [comment]
http://stackoverflow.com/questions/39864095/how-to-create-a-git-repository-in-memory/39864196

**Comment by BMorearty** [comment]
The `README` says you can use `Rugged::InMemory` but the gem doesn't seem to provide such a class.
