### ISSUE TITLE
rb_git_indexentry_toC randomly setting `assume-unchanged` flag?

### ISSUE THREAD

**Issue by jasonroelofs** [libgit2/rugged#636]
I have a really strange situation that may be a bug or just confusion on my part. Basically, I use Rugged to create files in a repository using the following code:

```ruby
oid = @repo.write(content, :blob)
index.add(path: path, oid: oid, mode: 0100644)
tree_oid = index.write_tree(@repo)
# Create Rugged::Commit with the tree_oid and write out to disk
```

For the most part this has been working fine but I've realized that when I go into the repository itself (the repo is not bare) and start using `git` commands, some files are flagged as `assume-unchanged`, such that local changes do not show up in `git status`. E.g., when I run `git ls-files -v` on files in the repo I see the following:

```
...
H themes/high-fiber/raw_page.tpl
h themes/high-fiber/sitemap.xml.tpl
h themes/high-fiber/stylesheets/base.css
...
```

Where `git ls-files -v` does the following:

```
-v
    Similar to -t, but use lowercase letters for files that are marked as assume unchanged (see git-update-index(1)).
```

I was led to this information when I found this SO answer: http://stackoverflow.com/a/28657085 and so I started diving down into how Rugged and libgit2 were writing these files, because there feels like a disconnect between how git reads index flags and how rugged is setting said flags.

My investigation led me to `rb_git_indexentry_toC` in `rugged_index.c`, specifically near the end of that function where `flags` is set:

```c
	if (!NIL_P(val)) {
		entry->flags &= ~GIT_IDXENTRY_VALID;
		if (rugged_parse_bool(val))
			entry->flags |= GIT_IDXENTRY_VALID;
	} else {
		entry->flags |= GIT_IDXENTRY_VALID;
       }
```

Now, in git, the flag for "assume-unchanged" is `0x8000` and called `CE_VALID`, which was ported to libgit2 as this `GIT_IDXENTRY_VALID`. However, all of the code in git that I've been able to find says that if this flag is set, then that means "assume-unchanged", so "valid" means "I will never change". I'm wondering if that expectation was confused here, and should the 'else' case in the code above be removed (as flags is initialized to 0)?

This `else` clause was added in https://github.com/libgit2/rugged/commit/771b784f44ce20dbbed7eaca0e659743d3add253.

For further reference, here's the implementation of `git ls-files` and its check on `CE_VALID` https://github.com/git/git/blob/f6727b0509ec3417a5183ba6e658143275a734f5/builtin/ls-files.c#L168

I'm able to solve my problem by forcing `valid` to `false` in the `add` call.

```ruby
index.add(path: path, oid: oid, mode: 0100644, valid: false)
```

The weirdest part is that this does not affect every file I create in the repository, and I haven't been able to track down why some files are flagged as such and some aren't. Is this a bug in rugged? Something that is just a confusion point when using git and libgit2 together?

Thanks

**Comment by ethomson** [comment]
Thanks for digging into this.  You're quite correct that this we shouldn't be setting this by default.  Would you be interested in submitting a PR to fix this up?

**Comment by jasonroelofs** [comment]
Sure. I'll get something together. Thanks for confirming!

**Comment by jasonroelofs** [comment]
PR open https://github.com/libgit2/rugged/pull/638, closing this Issue.
