### ISSUE TITLE
NameError: uninitialized constant Rugged::InMemory

### ISSUE THREAD

**Issue by isaac** [libgit2/rugged#681]
I am trying to create an in memory repository based on this part of the README: https://github.com/libgit2/rugged/blob/master/README.md#alternative-backends

I try to initialise a backend like this: `a_backend = Rugged::InMemory::Backend.new(opt1: 'setting', opt2: 'setting')`

This results in the following error: `NameError: uninitialized constant Rugged::InMemory`

Can anyone point me in the right direction?

I am using Rugged version 0.25.1.1

**Comment by BMorearty** [comment]
Same problem for me. The `README` says you can use `Rugged::InMemory` but the gem (0.27.0) doesn't seem to provide such a class.

**Comment by thelucid** [comment]
Getting the same error in 2021. Did anyone get any answers on this?

**Comment by carlosmn** [comment]
That backend does not exist in the repository.That is an example for how you can use a custom objectdb backend. I don't think such a backend ever made it into rugged.
