### ISSUE TITLE
Zlib::Inflate.new raises a Zlib::StreamError after requiring rugged

### ISSUE THREAD

**Issue by bsedat** [libgit2/rugged#705]
Cross-posting from prontolabs/pronto#23.

Rugged seems to be breaking zlib if I require it before creating the zlib inflater.

In a new irb console I can run:
```ruby
require 'rugged'
require 'zlib'
Zlib::Inflate.new(32 + Zlib::MAX_WBITS)
```
and it raises a `Zlib::StreamError`. Unfortunately there doesn't seem to be any useful information in the backtrace. Interestingly, swapping the ordering of the requires does not produce the error.

I'm running it in following environment from an alpine linux 3.6 docker container:
ruby -v: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-musl]
gem list | grep rugged: rugged (0.26.0).

**Comment by tenderlove** [comment]
It sounds like the gem installation of Rugged, and the installation of Ruby are linked against different implementations of libz (at least that is my guess).  Can you paste the output from `ldd` against `zlib.so` (in your Ruby installation) and against your `rugged.so` file?

**Comment by tenderlove** [comment]
Another option is to do this:

```
$ LD_TRACE_LOADED_OBJECTS=1 ruby -e'require "rugged"; require "zlib"'
```

```
$ LD_TRACE_LOADED_OBJECTS=1 ruby -e'require "zlib"; require "rugged"'
```

and see what the difference is.

**Comment by bsedat** [comment]
Hm, apparently `LD_TRACE_LOADED_OBJECTS` isn't supported by musl but I have the ldd output for you. Thanks so much for taking a look!

```
$ ldd /usr/lib/ruby/2.4.0/x86_64-linux-musl/zlib.so
ldd (0x55f7f22e7000)
libruby.so.2.4 => /usr/lib/libruby.so.2.4 (0x7fbe06d2a000)
libz.so.1 => /lib/libz.so.1 (0x7fbe06b13000)
libc.musl-x86_64.so.1 => ldd (0x55f7f22e7000)
libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7fbe068af000)

$ ldd /usr/lib/ruby/gems/2.4.0/gems/rugged-0.26.0/lib/rugged/rugged.so
ldd (0x55a0806e3000)
libruby.so.2.4 => /usr/lib/libruby.so.2.4 (0x7f9fd28a0000)
libc.musl-x86_64.so.1 => ldd (0x55a0806e3000)
libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f9fd263c000)
```

**Comment by tenderlove** [comment]
Well this is weird.  I'd expect both of them to link against libz, unless you've installed libgit2 and are linking against a system library (in which case I'd expect rugged.so to link against libgit2, but clearly it is not).

It looks like your libz is in `/lib`.  Can you paste the output of `ruby -rrbconfig -e'p RbConfig::CONFIG["LDFLAGS"]'`?  My next guess is that we need to provide Ruby's LDFLAGS to libgit2 when the rugged gem builds libgit2.

**Comment by bsedat** [comment]
```
$ ruby -rrbconfig -e'p RbConfig::CONFIG["LDFLAGS"]'
"-L. -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic"
```

**Comment by ethomson** [comment]
You can optionally compile zlib support in to libgit2, if you lack it on your system.  From the output of `ldd` above, it looks like that's what's been done here.  We basically include zlib 1.2.8 outright, we don't do anything wacky like name mangle the symbols.  As a result, I'm guessing that the loader has found those symbols in libgit2 first, instead of in the system's zlib, and that they're totally incompatible from an ABI standpoint.  💥

**Comment by ethomson** [comment]
I should clarify that:  libgit2 - if it does not detect zlib - will include its own.  There appears to be no option in the `CMakeLists.txt` to force it one way or another or fail if the system zlib cannot be found.

**Comment by tenderlove** [comment]
@ethomson it looks like @bsedat was able to compile Ruby and link it with a system zlib though.  IOW libgit2 *should* have used the system libz, but didn't, which says to me it's not searching `/lib` at compile time for some reason.

**Comment by tenderlove** [comment]
If Ruby was able to detect and use the system libz, it seems reasonable for libgit2 to do the same.  I just don't know by what means Ruby was able to find it.

**Comment by ethomson** [comment]
Hmm.  I'm not seeing where @bsedat actually compiled ruby though.  I assumed from:

> I'm running it in following environment from an alpine linux 3.6 docker container:

that it was the packaged ruby.  And I'm not at all familiar with Alpine Linux but I assume it uses binary containers.

If that's true then the [zlib-dev](https://pkgs.alpinelinux.org/package/edge/main/x86/zlib-dev) package may not be installed, so libgit2 could not find it at configure time.

**Comment by bsedat** [comment]
I can confirm that installing zlib-dev before installed rugged fixes the issue.

**Comment by ethomson** [comment]
Thanks for the confirmation @bsedat.  I think it makes sense for libgit2 to support some option to force a system zlib (or fail if not found) so that we can ensure that rugged is compatible with the Ruby zlib here...

We're doing some build system refactoring now so it seems reasonable that this be included.

**Comment by bsedat** [comment]
Appears to be fixed in newer versions of `rugged`. Thanks!
