### ISSUE TITLE
Diff from rugged is returning corrupted data

### ISSUE THREAD

**Issue by godfat** [libgit2/rugged#716]
I realized that blob in Git doesn't have encoding information, therefore there's probably no good way to make sure that diff won't cut in the middle of an Unicode character.

On the other hand, since the data is in valid encoding, could we make sure that the line like:

```
@@ -24,7 +24,7 @@ ...
```

Should never cut in the middle of an Unicode character? Or we could tell rugged that always return the whole line, therefore we never cut.

Note that if I just use `git diff` from command line, it doesn't cut in the middle of an Unicode character, but it would do with rugged.

Let me know if you need an reproducible case to study. I am working on making a simple script and a file content to reproduce it. You could find some more context around https://gitlab.com/gitlab-org/gitlab-ce/issues/35098

Thanks!

**Comment by ethomson** [comment]
Yes, a reproduction case here where we differ from git would be helpful.

**Comment by godfat** [comment]
@ethomson Thanks! Interestingly, I just realized that this doesn't always happen in some environments, so this must be something we could fix. I don't quite get what's the difference yet though.

Here's the minimum I could get: https://gist.github.com/godfat/9e8b2ed0b594667aa7dcb1bc2ccdd9ca

**Comment by godfat** [comment]
Clarification: No I could always reproduce this. I just made some silly mistake and thought it's working.

**Comment by godfat** [comment]
@ethomson Did you have luck to reproduce it?

**Comment by stanhu** [comment]
To be clear, this is a sample repository that is having issues: https://github.com/stanhu/rugged-encoding-test.

```shell
$ ruby test.rb | hexdump -C
00000000  64 69 66 66 20 2d 2d 67  69 74 20 61 2f 4a 61 70  |diff --git a/Jap|
00000010  61 6e 65 73 65 2e 6d 64  20 62 2f 4a 61 70 61 6e  |anese.md b/Japan|
00000020  65 73 65 2e 6d 64 0a 69  6e 64 65 78 20 64 64 34  |ese.md.index dd4|
00000030  36 39 63 39 2e 2e 63 61  66 30 32 32 64 20 31 30  |69c9..caf022d 10|
00000040  30 36 34 34 0a 2d 2d 2d  20 61 2f 4a 61 70 61 6e  |0644.--- a/Japan|
00000050  65 73 65 2e 6d 64 0a 2b  2b 2b 20 62 2f 4a 61 70  |ese.md.+++ b/Jap|
00000060  61 6e 65 73 65 2e 6d 64  0a 40 40 20 2d 32 34 2c  |anese.md.@@ -24,|
00000070  37 20 2b 32 34 2c 37 20  40 40 20 52 65 64 61 63  |7 +24,7 @@ Redac|
00000080  74 65 64 e3 81 a7 e3 81  af 2a 2a e3 83 ac e3 82  |ted......**.....|
00000090  a4 e3 83 a4 2a 2a e3 81  ab e3 81 8a e3 81 91 e3  |....**..........|
000000a0  82 8b 2a 2a 7a 49 6e 64  65 78 2a 2a e5 b1 9e e6  |..**zIndex**....|
000000b0  80 a7 e3 82 92 e5 88 b6  e5 be a1 e5 8f af e8 83  |................|
000000c0  bd e3 81 ab e3 81 99 e3  82 8b e3 0a 0a 2a 2a 7a  |.............**z|
000000d0  49 6e 64 65 78 e3 81 af  e3 82 b0 e3 83 ad e3 83  |Index...........|
# ...
$ git diff --no-color df3cddc22ad22db7feb5f55ee0aa6e99b5cabea0..a47beb14950ff4eac14568bd553778bd0ff12ce7 | hexdump -C
00000000  64 69 66 66 20 2d 2d 67  69 74 20 61 2f 4a 61 70  |diff --git a/Jap|
00000010  61 6e 65 73 65 2e 6d 64  20 62 2f 4a 61 70 61 6e  |anese.md b/Japan|
00000020  65 73 65 2e 6d 64 0a 69  6e 64 65 78 20 64 64 34  |ese.md.index dd4|
00000030  36 39 63 39 2e 2e 63 61  66 30 32 32 64 20 31 30  |69c9..caf022d 10|
00000040  30 36 34 34 0a 2d 2d 2d  20 61 2f 4a 61 70 61 6e  |0644.--- a/Japan|
00000050  65 73 65 2e 6d 64 0a 2b  2b 2b 20 62 2f 4a 61 70  |ese.md.+++ b/Jap|
00000060  61 6e 65 73 65 2e 6d 64  0a 40 40 20 2d 32 34 2c  |anese.md.@@ -24,|
00000070  37 20 2b 32 34 2c 37 20  40 40 20 52 65 64 61 63  |7 +24,7 @@ Redac|
00000080  74 65 64 e3 81 a7 e3 81  af 2a 2a e3 83 ac e3 82  |ted......**.....|
00000090  a4 e3 83 a4 2a 2a e3 81  ab e3 81 8a e3 81 91 e3  |....**..........|
000000a0  82 8b 2a 2a 7a 49 6e 64  65 78 2a 2a e5 b1 9e e6  |..**zIndex**....| 
000000b0  80 a7 e3 82 92 e5 88 b6  e5 be a1 e5 8f af e8 83  |................|
000000c0  bd e3 81 ab e3 81 99 e3  82 8b 0a 20 0a 20 2a 2a  |........... . **|
000000d0  7a 49 6e 64 65 78 e3 81  af e3 82 b0 e3 83 ad e3  |zIndex..........|
# ...
```

Note how the second (correct) version has on the penultimate line: `[82 8b] 0a 20 0a 20 [2a 2a]` vs `[82 8b] e3 0a 0a [2a 2a]` on the Rugged / Ruby version.

Visually this displays like so in my terminal:

```shell
$ ruby test.rb
diff --git a/Japanese.md b/Japanese.md
index dd469c9..caf022d 100644
--- a/Japanese.md
+++ b/Japanese.md
@@ -24,7 +24,7 @@ Redactedでは**レイヤ**における**zIndex**属性を制御可能にする�
# ...
$ git diff --no-color df3cddc22ad22db7feb5f55ee0aa6e99b5cabea0..a47beb14950ff4eac14568bd553778bd0ff12ce7
diff --git a/Japanese.md b/Japanese.md
index dd469c9..caf022d 100644
--- a/Japanese.md
+++ b/Japanese.md
@@ -24,7 +24,7 @@ Redactedでは**レイヤ**における**zIndex**属性を制御可能にする
# ...
```

Or using unidump, you can see this visually:

![image](https://user-images.githubusercontent.com/963826/36486820-4ac48320-16d4-11e8-81f8-5ca1315d744e.png)

**Comment by stanhu** [comment]
The problem appears to be a buffer overrun here: 

https://github.com/libgit2/libgit2/blob/809b0ca6b9b6a5648b8e802a9f0c6a0821257595/src/diff_driver.c#L493-L495

It appears that that `buf` in `func_line` is 80 characters https://github.com/libgit2/libgit2/blob/809b0ca6b9b6a5648b8e802a9f0c6a0821257595/src/xdiff/xemit.c#L132-L135, so when the context line is longer than that (130 bytes in the example above), there is a buffer overrun.

I tried to cap it in #4540, but this breaks all the tests. Changing `buf[80]` to `buf[256]` works around the problem.

**Comment by stanhu** [comment]
Yeah, it looks like this may be an issue with truncating the hunk header at 80 characters:

```ruby
irb(main):022:0> test = "Redactedでは**レイヤ**における**zIndex**属性を制御可能にすることで、この課題を解決しています"
=> "Redactedでは**レイヤ**における**zIndex**属性を制御可能にすることで、この課題を解決しています"
irb(main):023:0> foo.force_encoding('ASCII-8BIT')[0..80]
=> "Redacted\xE3\x81\xA7\xE3\x81\xAF**\xE3\x83\xAC\xE3\x82\xA4\xE3\x83\xA4**\xE3\x81\xAB\xE3\x81\x8A\xE3\x81\x91\xE3\x82\x8B**zIndex**\xE5\xB1\x9E\xE6\x80\xA7\xE3\x82\x92\xE5\x88\xB6\xE5\xBE\xA1\xE5\x8F\xAF\xE8\x83\xBD\xE3\x81\xAB\xE3\x81\x99\xE3\x82\x8B\xE3\x81"
```

It looks like somehow `git` includes the last couple bytes to avoid this.

**Comment by stanhu** [comment]
Aha! I figured it out by tracing the behavior of git. It looks like git does truncation of the hunk header based on UTF-8 boundaries in a function called `sane_truncate_line` here:

https://github.com/git/git/blob/e3a80781f5932f5fea12a49eb06f3ade4ed8945c/diff.c#L1927-L1941
