### ISSUE TITLE
Add support for RecievePack and UploadPack

### ISSUE THREAD

**Issue by devchild** [libgit2/rugged#724]
I was hoping that this support for RecievePack and UploadPack could be added to this library.

The implementation should allow us to implement a http git server. Today to only way around this is by called git directly, this isn't an option when using custom backends.

**Comment by carlosmn** [comment]
This is currently outside of the scope of the library. While it would be interesting to see how something could be generic enough to make it into the library while providing sufficient functionality to make it useful, it's not something that's going to be done in the foreseeable future.
