### ISSUE TITLE
Tree#diff: unexpected behavior of option :include_untracked_content

### ISSUE THREAD

**Issue by alexey-igrychev** [libgit2/rugged#728]
Commit#diff_workdir refers to Tree#diff_workdir.

> [Doc: Tree#diff_workdir](http://www.rubydoc.info/github/libgit2/rugged/Rugged/Tree#diff_workdir-instance_method)

Returns a diff between a tree and the current workdir.

The tree object will be used as the “old file” side of the diff, while the content of the current workdir will be used for the “new file” side.

See Rugged::Tree#diff for a list of options that can be passed.
> [Doc: Tree#diff](http://www.rubydoc.info/github/libgit2/rugged/Rugged%2FTree.diff)

:include_untracked_content | if true, untracked content will be contained in the the diff patch text.
-- | --

> Problem

```ruby
repo 	= Rugged::Repository.new('.')
commit 	= repo.head.target_id
options = { 
  include_untracked: true, 
  include_untracked_content: true, 
  recurse_untracked_dirs: true 
}
diff    = repo.lookup(commit).diff_workdir(**options)
```

I have untracked files in diff but I cannot get context of ones.

```ruby
patch = diff.patches.first 
patch.delta
=>  <Rugged::Diff::Delta:11857500 {old_file: {:oid=>"0000000000000000000000000000000000000000", :path=>"test", :size=>0, :flags=>6, :mode=>0}, new_file: {:oid=>"0000000000000000000000000000000000000000", :path=>"test", :size=>8, :flags=>10, :mode=>33188}, similarity: 0, status: :untracked>
patch.to_s
=> ""
```

**Comment by tjk** [comment]
Looks like a documentation issue. It should be `show_untracked_content: true` (not `include_untracked_content`)(https://github.com/libgit2/libgit2/blob/ac0f2245510f6c75db1b1e7af7ca01c15dec26bc/include/git2/diff.h#L156) and make sure to pass `recurse_untracked_dirs: true` as well if you need that.
