### ISSUE TITLE
`each_line` causes segfault with ruby 2.5.0 MRI

### ISSUE THREAD

**Issue by npetkov** [libgit2/rugged#729]
I was investigating why [pronto](https://github.com/prontolabs/pronto) fails with some weird errors around [this line](https://github.com/prontolabs/pronto/blob/6d21d1f4991f4f3f3871217bd034536cae93d915/lib/pronto/git/patch.rb#L22) and after some debugging came to the conclusion that there is an issue between the current version of rugged and ruby 2.5.0.

It's easy enough to reproduce, just clone the repo as described in the docs and try running the test suite. It'll fail, causing a segfault. During the compilation process, several "division by zero" warnings are thrown.

My environment:

* macOS 10.13.1
* cmake 3.10.1
* ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

I'll try running the test suite under ubuntu as well and will update this issue accordingly.

Logs/traces:

[compile.log](https://github.com/libgit2/rugged/files/1597717/compile.log)
[test_run.log](https://github.com/libgit2/rugged/files/1597718/test_run.log)

**Comment by arthurschreiber** [comment]
@npetkov Looks like you're on the right track! If you open a PR with the fixes you suggested, I'll review and merge ASAP! 👍

**Comment by arthurschreiber** [comment]
@npetkov Nevermind, I looked into this and opened https://github.com/libgit2/rugged/pull/730 to fix the issue - thanks for the 🕵️ work done for tracking this down!

**Comment by npetkov** [comment]
Just forked the repo and committed a fix, but now looking at #730 it's clear that your solution is far superior. Glad I could help!
