### ISSUE TITLE
Ruby 2.5 - new release

### ISSUE THREAD

**Issue by npetkov** [libgit2/rugged#738]
Hi, now that ruby 2.5 is supported, can we expect a new release soon?

Cheers,
Nikolay

**Comment by carlosmn** [comment]
libgit2 is getting ready for a new release. Once the library releases, we'll update and cut the new release.

**Comment by shaneog** [comment]
@carlosmn `libgit2` has released several versions since your comment?

Do you think a Ruby 2.5 compatible release is in the near future for `rugged`?

**Comment by carlosmn** [comment]
There have been no major/minor releases that would cause us to cut the new gem.
