### ISSUE TITLE
Whitespaced attribute values

### ISSUE THREAD

**Issue by raphaelyancey** [libgit2/rugged#764]
The use case being [linguist](https://github.com/github/linguist), how are we supposed to provide whitespaced values in a `.gitattribute`?

```
*.pdt linguist-detectable=true linguist-language="Pure Data"
```
```
irb(main):018:0> repo.fetch_attributes('./test.pdt')
=> {"Data\""=>true, "linguist-detectable"=>"true", "linguist-language"=>"\"Pure"}
```

There are [a](https://github.com/douban/linguist/blob/master/linguist/libs/languages.yml#L710) [few](https://github.com/douban/linguist/blob/master/linguist/libs/languages.yml#L714) [whitespaced](https://github.com/douban/linguist/blob/master/linguist/libs/languages.yml#L840) [languages](https://github.com/douban/linguist/blob/master/linguist/libs/languages.yml#L1119) names that one would want to override.

I tested with different escapings but none seems to work.

**Comment by carlosmn** [comment]
The `.gitattributes` format does not allow for whitespace or quoting. If linguist wants to only rely on that, it must come up with a workaround.
