### ISSUE TITLE
Rubygems contains v0.28.1 but the repository doesn't

### ISSUE THREAD

**Issue by jeroenj** [libgit2/rugged#802]
`0.28.1` is available on Rubygems: https://rubygems.org/gems/rugged/versions/0.28.1.

But the repository does not seem to contain it and currently [`version.rb`](https://github.com/libgit2/rugged/blob/f26ed3e2fe39204768c4a02a25d910bd62871c3c/lib/rugged/version.rb#L7) still lists `0.28.0`.

Dit a `0.28.1` release somehow got pushed incorrectly?

**Comment by cfillion** [comment]
Look like it's in the [maint/v0.28](https://github.com/libgit2/rugged/commits/maint/v0.28) branch (26608e76689724180c7dbd0abcd69ea212ff61f6).

**Comment by jeroenj** [comment]
I see that a `v0.28.2` tag has been pushed now and that branch indeed shows up in https://github.com/libgit2/rugged/branches. I guess it was just nog pushed to GitHub when I opened the issue.
