### ISSUE TITLE
v0.28.3 errored with symbol lookup error

### ISSUE THREAD

**Issue by sikachu** [libgit2/rugged#813]
Hello,

We have a CI server that runs [pronto](https://github.com/prontolabs/pronto) on all of our PRs. Our CI server always do a `gem install pronto` and hence always installing the latest version of rugged.

Starting today, after the release of rugged v0.28.3, we noticed that our CI started to fail with a symbol lookup error:

```
/usr/local/bin/ruby: symbol lookup error: [working path]/vendor/bundle/gems/rugged-0.28.3/lib/rugged/rugged.so: undefined symbol: pcreposix_regcomp
Exited with code 127
```

We use CircleCI as our CI provider, and here's the server environment:

```
Build-agent version 1.0.13455-a66ea3ac (2019-08-12T21:51:13+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux 6dc139e41d1d 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 Linux
Starting container circleci/ruby:2.6.3-node-browsers
  image is cached as circleci/ruby:2.6.3-node-browsers, but refreshing...
2.6.3-node-browsers: Pulling from circleci/ruby
Digest: sha256:14d1773980b16ab95ccf8dfbde1258ed54ad31ee5b7aec4f6c47455a264a88bb
Status: Image is up to date for circleci/ruby:2.6.3-node-browsers
  using image circleci/ruby@sha256:14d1773980b16ab95ccf8dfbde1258ed54ad31ee5b7aec4f6c47455a264a88bb
```

Would you mind looking into this issue? Please let me know if you'd like further information.

Thank you very much.

**Comment by sikachu** [comment]
Looks like a similar issue was reported on Pronto side: https://github.com/prontolabs/pronto/issues/355

**Comment by vytasmk** [comment]
Also here getting error using Redmine with Gitolite plugin.

`ruby: symbol lookup error: /usr/local/bundle/gems/rugged-0.28.3/lib/rugged/rugged.so: undefined symbol: pcreposix_regcomp`

**Comment by stanhu** [comment]
Ran into this as well. The tag for v0.28.2 is wrong as well, so it was hard to do a diff. I think this commit https://github.com/libgit2/rugged/commit/7c328ec27e04c26424668e20216d6656bbcbdd87 has something to do with it?

**Comment by daveverwer** [comment]
I'm also seeing this after updating to 0.28.3. I'm getting this:

```
/home/app/shared/bundle/ruby/2.6.0/bin/rake update:package:repositories: symbol lookup error: /home/app/shared/bundle/ruby/2.6.0/gems/rugged-0.28.3/lib/rugged/rugged.so: undefined symbol: pcreposix_regcomp
```
Running Ruby 2.6.3 on Ubuntu 18.04

**Comment by carlosmn** [comment]
It turns out I messed up uploading the gem and it comes from a newer version of the code where libgit2 tries to link against the system libpcre but there's a bug where the `.pc` file doesn't list it so we fail to link to it.

We work around that in master, but either way, I've pushed up rugged 0.28.3.1 which contains the correct version of the code.
