### ISSUE TITLE
rugged 0.28.3 with r10k 3.3.0 fails with malloc error

### ISSUE THREAD

**Issue by kbpease** [libgit2/rugged#815]
I am using rugged as the back-end git provider for r10k, which is run on my Puppet server node to deploy puppet control repos.

Since the 0.28.3 release, the r10k tool crashes with a malloc error during execution with the following backtrace:

https://gist.github.com/kbpease/80371945b041d05e3349403dc6e5f9d1

Reverting the installed rugged version to 0.28.2 restores any system exhibiting this behavior back to a functional state.

I don't have any other data I can provide right now, but if there's anything else I can supply for troubleshooting purposes, please let me know and I'll try to provide it.

**Comment by ethomson** [comment]
Hi @kbpease, thanks for the report.  Since the crash is around the regex code, could you upgrade to the just-released [0.28.3.1](https://github.com/libgit2/rugged/releases/tag/v0.28.3.1) and see if that changes anything?

**Comment by carlosmn** [comment]
I can't see that gist, but it's likely that it's the same issues as #813 

I have pulled the 0.28.3 gem and pushed a replacement for it.

**Comment by kbpease** [comment]
@ethomson, @carlosmn - upgrading to 0.28.3.1 resolves the issue we're seeing - thanks for the fast response!
