### ISSUE TITLE
Unexpected HTTP status code: 401

### ISSUE THREAD

**Issue by jagdishdasani** [libgit2/rugged#865]
Getting below error while cloning the git repo.  

Rugged gem version: **0.21.4**
Ruby version: **ruby 2.2.1p85**
```
Rugged::NetworkError: Unexpected HTTP status code: 401
	from (irb):175:in `clone_at'


```

**Comment by carlosmn** [comment]
Did you set up any authentication? Can you reproduce with the current code?
